### ISSUE TITLE
Create Sidetree DID Resolver

### ISSUE THREAD

**Issue by fqutishat** [hyperledger/aries-framework-go#100]
Write sidetree resolver that call sidetree restapi to resolve did doc.

epic #86

**Comment by OR13** [comment]
Probably want to just support the universal resolver and pressure Microsoft / Transmute to get their DID implementations into the Universal Resolver.

There is really no excuse for not adding your DID Method to the universal resolver:

https://github.com/decentralized-identity/universal-resolver/issues/41

I have a todo to get `did:github` and `did:elem` into it (elem is a sidetree ethereum implementation).

**Comment by troyronda** [comment]
@OR13 We are also planning to support universal resolver: https://github.com/hyperledger/aries-framework-go/issues/99

**Comment by troyronda** [comment]
It looks like we can contain this item within #99 for resolution ops (for now):

- [Sidetree resolution](https://github.com/decentralized-identity/sidetree/blob/master/docs/protocol.md#did-document-resolution)
  - Example: `GET /did:sidetree:exKwW0HjS5y4zBtJ7vYDwglYhtckdO15JDt1j5F5Q0A`
- [HTTPS binding](https://w3c-ccg.github.io/did-resolution/#bindings-https)
  - Example: `GET /1.0/identifiers/did:sov:WRfXPg8dantKVubE3HX8pw`

We should ensure that #99 has flexibility on the base path on the server URL. @fqutishat @kdimak.

As such, I'll close this story for now.
