### ISSUE TITLE
Resolving peer DID from storage

### ISSUE THREAD

**Issue by talwinder50** [hyperledger/aries-framework-go#106]
We need a did:peer method resolver to be plugged by default into didresolver.DIDResolver. This resolver needs to resolve peer DID documents from the storage.Store.

This issue is derived from #97

**Comment by talwinder50** [comment]
@llorllale how this is different than https://github.com/hyperledger/aries-framework-go/issues/79

**Comment by llorllale** [comment]
@talwinder50 closed as duplicate of #79
