### ISSUE TITLE
Replace DIDCommMsg type with map[string]interface{}

### ISSUE THREAD

**Issue by soluchok** [hyperledger/aries-framework-go#1065]
Replace DIDCommMsg type with map[string]interface{}

All messages in the framework should be generic. It allows us to get easily common information e.g `type`, `id`, `~thread`, etc. Because we are using `JSON` based messages it is enough to represent the message as `map[string]interface{}`. Also, we will be able to modify our message without knowing its type.

P.S The idea is to generalize messages across the system(framework)!

**Comment by llorllale** [comment]
I think something similar should be done with VCs as well.
