### ISSUE TITLE
JS Worker Scaffolding

### ISSUE THREAD

**Issue by troyronda** [hyperledger/aries-framework-go#1069]
Part of #1064 

- [x] Create a new cmd package:`aries-worker` or `aries-wasm-worker` or `aries-js-worker`
- [x] Create package for acting as a JS Worker: `jsworker`
- [x] JS Worker package should instantiate a event dispatcher package that interacts with JavaScript
   - [x] Register for worker events from JavaScript
   - [x] Post events to JavaScript
- [x] Create wrapper JavaScript: 'aries-worker.js'
   - [x] Loads WASM
- [x] Create test page and JavaScript for the JS Worker interface.
   - [x] Send and receive events with the WASM.

**Comment by llorllale** [comment]
@troyronda  all of these are done
