### ISSUE TITLE
DIDExchange Request - Add recKey to the Router

### ISSUE THREAD

**Issue by rolsonquadras** [hyperledger/aries-framework-go#1100]
Add recKeys generated as part of new DIDDoc(did-communication service) to the router (#1073).

**Comment by llorllale** [comment]
@rolsonquadras the description is a misleading: we're not *updating* the `service` section of any any did doc - we're creating a *new* did doc with the appropriate `service` section that includes the routing bits.

**Comment by rolsonquadras** [comment]
@llorllale agreed. Updated the description.
