### ISSUE TITLE
Should pkg/framework/aries be higher in the folder hierarchy?

### ISSUE THREAD

**Issue by troyronda** [hyperledger/aries-framework-go#114]
Example: should this package be directly under pkg instead of pkg/framework?

From this thread: https://github.com/hyperledger/aries-framework-go/pull/88#issuecomment-521372936

**Comment by rolsonquadras** [comment]
It was originally inside framework in the original PR, but moved to (/framework/aries](https://github.com/hyperledger/aries-framework-go/pull/88#discussion_r313067770) folder.

It makes sense to have inside framework pkg. Something like `aries := framework.New()`

**Comment by troyronda** [comment]
@rolsonquadras I'm still not a fan of having it in the framework folder itself. It's not a parent of the other frameworks.

**Comment by rolsonquadras** [comment]
@troyronda what are you suggesting then? To have '/pkg/aries' instead of '/pkg/framework/aries' ?

**Comment by troyronda** [comment]
@rolsonquadras Mainly a question rather than a suggestion :).

**Comment by sudeshrshetty** [comment]
`pkg/framework/aries` should be fine, we will add more under `pkg/framework` going in future.

**Comment by sudeshrshetty** [comment]
@troyronda 
 I am not sure about package `protocol` inside `didcomm`, protocols are like message families, can we move them out under pkg and have
pkg/protocols
pkg/protocols/exchange
pkg/protocols/handler
pkg/protocols/exchange/controller (if needed)
.
.
.
??
`didcomm` should have something related to transport. Inbound, outbound etc and related communication related APIs

**Comment by llorllale** [comment]
@troyronda @rolsonquadras 

With regards to this statement:

> I am wondering if we should have this package directly under pkg (since it is effectively the default entry point for developers).

The framework isn't there yet - we don't yet offer a single entrypoint for the user. Currently `framework.Aries` and `didexchange` are disjoint APIs. Perhaps we can defer this question til later.

**Comment by troyronda** [comment]
@llorllale The pattern for the 'normal' user of the framework will be to instantiate an aries framework, get a context, and use that context in the other packages. We don't force it (of course) but this would be the typical pattern.

**Comment by llorllale** [comment]
@troyronda it seems unusual to me that instantiating a "framework" only provides you with a "context" object that you then have to manually pass around to APIs in individual packages.

I'm reserving my opinion on this until the picture becomes clearer. I'm personally looking forward to the outcome of #11 because I think it's a mayor missing piece in the framework.

**Comment by troyronda** [comment]
@llorllale Passing an object that provides shared resources (called context here) allows is to avoid anti-patterns such as a singletons holding the resource and forcing a particular implementation of an underlying library.

Singletons supplying shared resources also leads to more coupling (and a less flexible design).

Re: passing around a context:
Our goal is a framework that allows building new functionality and protocols - both inside and outside the repo.

We want a flexible and decoupled design.

**Comment by troyronda** [comment]
Re: the Aries framework package:

This package provides a typical implementation of the shared resource. This is accomplished by instantiating a set of factories based on options (and possibly configuration).

This is the same pattern as we used in fabric-sdk-go.

**Comment by troyronda** [comment]
Re: #111
The state machine object would be instantiated from within the did-exchange package. There shouldn’t be a specific correlation back to the Aries framework package.

Of course, I assume that a mechanism for registering against the inbound transport ... for example ... as a generic correlation.

**Comment by llorllale** [comment]
@troyronda see my thoughts about protocol states [here](https://github.com/hyperledger/aries-framework-go/issues/111#issuecomment-521646754) - hopefully it clears things up a bit.

(I suggest we keep design discussions for protocol state in #111)
