### ISSUE TITLE
Introduce - the protocol should not depend on thread decorator

### ISSUE THREAD

**Issue by soluchok** [hyperledger/aries-framework-go#1157]
Currently, the protocol depends on `threadID`. What does it mean? When protocol communicates with three participants it uses the same `threadID` per communication. e.g Alice wants to introduce Carol to Bob. Messages in the protocol will look like:
* Alice sends message to Bob `{"@id":"111","~thread":{"thid":"000"}}`
* Alice sends message to Carol `{"@id":"222","~thread":{"thid":"000"}}`

The example above clearly says that Alice-Bob and Alice-Carol have the same threadID `000`.It was done in that way to identify the context in the protocol. The protocol relies on that thread. It is how we understand that the introduction is related to three persons. Otherwise, there is no way to understand that participants are in the same context.
According to our RFCs which describe JSON-based communication there should not be a message with the same ID (messageID is unique). Also, RFCs say `threadID` is the ID of the first message. Which makes impossible to have two communication with the same `threadID`. It means that the introduce protocol does not follow logic like it is described in RFC.

Let's imagine the use case when Alice wants to introduce Carol to Bob. Alice sends two proposal messages(simultaneously) through the introduce `Client`. 
Messages might look like:
* Alice sends message to Bob `{"@id":"111"}`
* Alice sends message to Carol `{"@id":"222"}`

According to the example above threads would be `~thread":{"thid":"111"}` and `~thread":{"thid":"222"}`. Currently, our HandleOutbound function allows us to send only one message. This means that we will send two proposals independently. The protocol will not know that messages are related to each other(same context). It is an issue.

Possible solutions:
* allow HandleOutbound function to send more than one message `HandleOutbound(msgs ..DidMsgWithDestination)`. (a bit complicated solution)
* add an additional field to the Proposal message e.g `ContextID`

An example of how Proposal might look like for the internal usage.
```
type Proposal struct {
	....
       // ContextID is an internal field that allows the protocol to identify and connect independent 
       // threads into the same context. The field will be ignored in the JSON message.
	ContextID     string            `json:"-"`
}
```

NOTE: Having a `contextID`, allows us to create a connection map e.g `map[thid]=contextID`. By `contextID` we can get a list of the threads e.g `map[contextID]=[]thids`.

**Comment by troyronda** [comment]
@soluchok Adding correlatable IDs to messages is not a desirable solution. i.e, no contextID.

**Comment by troyronda** [comment]
i think the solution should avoid making it look like a correlation field is in the on-the-wire message schema.

**Comment by llorllale** [comment]
@soluchok use `~thread.pthid`

**Comment by soluchok** [comment]
@llorllale Thanks, I will do that.

**Comment by llorllale** [comment]
@soluchok I think Troy may have a point. `pthid` seems to be used for cases when two parties *that are already interacting* to correlate a new interaction with the old one. But in this case, `proposal` starts a completely new interaction with an agent who is not/should not be aware of the parent interaction. Therefore, correlation should be done internally by the introducer.
