### ISSUE TITLE
Support SQL Storage Provider (sqlite)

### ISSUE THREAD

**Issue by troyronda** [hyperledger/aries-framework-go#1166]
Support usage of a SQL storage provider backend.

In particular, start by supporting sqlite.

**Comment by talwinder50** [comment]
@talwinder50

**Comment by llorllale** [comment]
@talwinder50 we need support for MySQL first right now.

**Comment by talwinder50** [comment]
Can you change description from sqlite to mysql. Can create a separate task for sqlite
