### ISSUE TITLE
DidResolver.Read() should return a did.Doc

### ISSUE THREAD

**Issue by llorllale** [hyperledger/aries-framework-go#118]
`Didresolver.Read()` should return a `did.Doc` as opposed to a slice of bytes:

https://github.com/hyperledger/aries-framework-go/blob/295e2172fc183e3442e16dac96352ea3ca8e89a8/pkg/framework/didresolver/api.go#L23-L26

**Comment by fqutishat** [comment]
@troyronda @llorllale Read method can return did doc or resolution-result

From spec:

If the value to of result-type input option is "resolution-result":
Construct a DID Resolution Result and populate it with the output DID Document as well as metadata about the processes that produced the result (see § 6. DID Resolution Result. This is called the output DID Resolution Result.
Return the output DID Resolution Result.

**Comment by troyronda** [comment]
I agree that we shouldn't have a typeless result like []byte.

One alternative solution is two split the functions such that each has the correct return type.
