### ISSUE TITLE
Controller API for connections protocol

### ISSUE THREAD

**Issue by sudeshrshetty** [hyperledger/aries-framework-go#121]
epic #67

Add below endpoints under connection protocol

### **connection**
GET ​/connections Query agent-to-agent connections
GET ​/connections​/{id} Fetch a single connection record
POST ​/connections​/create-invitation Create a new connection invitation
POST ​/connections​/receive-invitation Receive a new connection invitation
POST ​/connections​/{id}​/accept-invitation Accept a stored connection invitation
POST ​/connections​/{id}​/accept-request Accept a stored connection request
POST ​/connections​/{id}​/establish-inbound​/{ref_id} Assign another connection as the inbound connection
POST ​/connections​/{id}​/remove Remove an existing connection record

**Comment by troyronda** [comment]
These endpoints should be marked superseded by did-exchange. New clients should use did-exchange.

Ie this is deprecated.
