### ISSUE TITLE
API design guidelines: how to represent "not found"

### ISSUE THREAD

**Issue by llorllale** [hyperledger/aries-framework-go#126]
This blocks PR #120 

I submit the following question to the community: *how do we best represent a "not found" result in an API's design?* The outcome from this discussion will result in a consistent API design across all packages documented in a markdown doc. Opinions will be collected until august 19th 3pm EDT. (feel free to submit an issue after the deadline in case you disagree with the outcome by the time the deadline arrives)

I posed this question to `#newbies` on the gophers slack [here](https://gophers.slack.com/archives/C02A8LZKT/p1565991198350000) (note - discussion may not be available by the time you read this as per the channel's chat log retention policies).

Summarizing the responses from `#newbies`:

* 3 responses in total
* All 3 responses were in favor of signalling "not found" as an *error*
* In terms of Dave Cheney's [Don't just check errors, handle them gracefully](https://dave.cheney.net/2016/04/27/dont-just-check-errors-handle-them-gracefully) article:
   * 2/3 responses were in favor of "sentinel errors"
   * 1/3 was in favor of the approach described in "Assert errors for behaviour, not type"

The responses surprised me because representing "not found" as an error is unusual to me coming from a language where errors are exceptions (an alternative, "third return path" resulting from calling a function) and where there exist monadic data types such as `Optional` or `Maybe` that more clearly convey the idea that "you may or may not obtain a result from this input".

I vote for representing "not found" as a `nil` data type and a `nil` error because I don't see much structural difference in the following variations of consumer code of APIs while at the same time we could save a little complexity in terms of API params:

```go
// bool return param
if result, found, err := api.Get(); err != nil {
  // :(
} else {
  if !found {
    // :(
  }

  // :)
}

// use 'nil' as "not found"
if result, err := api.Get(); err != nil {
  // :(
} else {
  if result == nil {
    // :(
  }

  // :)
}

// one way to use specific error type as "not found"
if result, err := api.Get(); err != nil {
  switch err.(type) {
    case ErrNotFound:
      // :(
    default:
      // :(
  }
} else {
  // :)
}

// another way to use specific error type as "not found"
if result, err := api.Get(); err != nil {
  if err == ErrNotFound {
    // :(
  }

  // :(
} else {
  // :)
}

// yet another way to use specific error type as "not found"
type ErrNotFound interface {
  error
}

func IsNotFound(e error) bool {
  tmp, ok := err.(ErrNotFound)
  return ok
}

if result, err := api.Get(); err != nil {
  if IsNotFound(err) {
    // :(
  }

  // :(
} else {
 // :)
```

**Comment by troyronda** [comment]
It looks like I agree with one of the responders on the gophers slack.

“By and large, if something returns a non-nil error the first value is ignored.”

I think (nil, nil) *should not be used* for Not Found.

**Comment by troyronda** [comment]
[HTTP 4xx status codes](https://tools.ietf.org/html/rfc7231#section-6.5) are called Client Errors as in:

> the client seems to have erred.

I am inclined to think typical NotFound cases are the same - the client seems to have erred by asking for a resource that doesn’t currently exist.

I think we should use an explicit error for these cases.

**Comment by troyronda** [comment]
The additional complexity of including the sentinel in the API and checking
> if err == ErrNotFound
is a trivial difference compared to checking for nil. 

With NotFound, we are explicitly documenting the case and not breaking the social convention that the first value should be ignored on non-nil.

**Comment by troyronda** [comment]
Another example in golang is in the [os stdlib package](https://golang.org/pkg/os/#Open)
has the example error `open file.go: no such file or directory`

and the method [IsNotExist](https://golang.org/pkg/os/#IsNotExist)

> IsNotExist returns a boolean indicating whether the error is known to report that a file or directory does not exist. It is satisfied by ErrNotExist as well as some syscall errors.

**Comment by troyronda** [comment]
[Example](https://crawshaw.io/blog/xerrors) using xerrors.Is

`xerrors.Is(err, taildb.ErrNotFound)`
(see version 4).

This is actually pretty nice as you also get an error string that gives you context.
> taildb: "my-key": key not found.

I’m thinking we should do this style.

**Comment by llorllale** [comment]
I agree `xerrors.Is()` is a better alternative than sentinel error values because implementations can safely add context to them without breaking the client code idiom `if xerrors.Is(err, aries.ErrNotFound)`. I also agree the difference between checking whether `err == aries.ErrNotFound` vs `result == nil` is trivial.

The design of `database/sql` is irrelevant because there is no possibility in our use cases of returning iterators: *either a single result is found or nothing is found.* 

I am left to wonder why an API should assume "not found" is an error.

*The API simply did not find data that matched the input criteria.* There was no error in processing this request. **It should be up to the client to decide whether 'not found' is an error condition**. Consider any search engine on the planet: does it return a `404` error if the search terms don't match any records? Do your trousers return an error when you reach in your pockets and can't find anything?

Answer: no.

**Comment by llorllale** [comment]
I was out-voted on this. :(

From what I understood, the reason is that Golang developers expect the return value to be useful if no errors are returned.
