### ISSUE TITLE
Optional Arguments for APIs

### ISSUE THREAD

**Issue by llorllale** [hyperledger/aries-framework-go#127]
Regarding PRs #120 and #117 :

I was directed towards Dave Cheney’s article [Functional options for friendly APIs](https://dave.cheney.net/2014/10/17/functional-options-for-friendly-apis) where he shares his thoughts on designs for optional parameters in APIs. Dave ends with a proposal for functional arguments that are optionally passed to a type constructor. There is no question this design is superior to having a single constructor with lots of arguments.

However:

**Dave’s design is overkill for 99% of use cases and imposes an unnecessary tax on both the maintainer and the consumer of these APIs.**

(Developers integrating with these APIs are consumers, and so are readers (aka. code reviewers)).

### My proposal

A *simpler* alternative: two constructors, one is default, the other accepts a config struct:

```go
package didresolver

type Options struct {
    ResolutionResult bool
    VersionID interface {}
    VersionTime string
    NoCache bool
}

func Default() DidMethod {...}

func Custom(options ...Options) DidMethod {...}
```

#### In terms of usage?

Decreased verbosity: occurrences of the symbol `didresolver` is decreased. The magnitude of this benefit increases linearly with the number of optional parameters:

```go
package consumer

import "github.com/hyperledger/aries-framework-go/pkg/framework/didresolver"

func CurrentDesign() {
    // Default
    resolver := didresolver.New()

    // Custom
    resolver := didresolver.New(
        didresolver.WithResolutionResult(didresolver.ResolutionResult),
        didresolver.WithVersionID("123"),
        didresolver.WithNoCache(),
    )
}

func MyDesign() {
    // Default
    resolver := didresolver.Default()

    // Custom
    resolver := didresolver.Custom(didresolver.Options{
        ResultType:  didresolver.ResolutionResult,
        VersionId:    "123",
        NoCache:     true,
    })
}
```
#### In terms of maintenance?

Decreased number of unit tests: reducing the set of options to a [value object](https://en.wikipedia.org/wiki/Value_object) renders tests for them *needless*.

####  In terms of usage?

Nothing as far as I can see.

The symbol `Default` clearly signals the possibility of custom `DidMethod`s such that a developer consuming this API would seek out alternatives if required. This means this design has no added confusing aspects.

#### In terms of maintenance?

N/A. We *improve* maintainability by reducing the number of artifacts we need to test.

Any validations and/or computations can be extracted unto their own functions (whether static or member functions) of the constructor’s type.

**Comment by troyronda** [comment]
I disagree.

- Documenting option methods is cleaner than fields. They format nicely in GoDoc.
- Methods are more flexible. They can transform the arguments into internal types.
- Similar options can be grouped together in a single option method.

The methods names you chose Default and Custom are not idiomatic.

**Comment by llorllale** [comment]
* I don't see any problem with readability of Godocs on structs. [Example](https://godoc.org/golang.org/x/crypto/ssh#ClientConfig)
* There are several strategies around transforming args - no need for functional options
* If multiple args are required for a single option then the option's abstraction was defined at the wrong level.
* Dave's example with `0` for port number was silly. I definitely expect the default value of `Port` to be a random port. So Dave's problem was the wrong definition of what the default behavior was. You will run into the same problems and solutions if you make a similar mistake with both functional and structural option types
* I could not find this rule properly laid out anywhere. Best I found was some stackoverflow posts and all that seemed to be required was to have `NewXXX` constructors *if there exist more than one exported type in that package*. That is not the case here.
* You're entitled to your opinion. I don't hold the same view: there is plenty of repetitiveness in Go code and it makes my job as a reviewer harder than it should be. Removing that extra `didresolver` prefix helps me. And I liked having `Default` and `Custom` ctors - makes it so much more semantically meaningful.
* No - this pattern makes it *required* to test options of even the most mundane type. Take a look at [these](https://github.com/hyperledger/aries-framework-go/blob/295e2172fc183e3442e16dac96352ea3ca8e89a8/pkg/framework/didresolver/api_test.go#L15) set of tests and see how the implementations are merely assigning values to struct fields

**Comment by llorllale** [comment]
I was out-voted on this. :(

From what I understood, Golang developers are used to this idiom thanks for Dave Cheney's article, and I was pointed to the `grpc` package as an example.
