### ISSUE TITLE
Allow WASM filename to be parametrized 

### ISSUE THREAD

**Issue by troyronda** [hyperledger/aries-framework-go#1277]
Some HTTP server deployments prefer to decide whether or not to compress assets. They may also choose the compression encoding based on the client capabilities.

In this case, the asset should be uncompressed in the server path and the file extension should simply be .wasm 

The Aries JS constructor should allow the filename to be customized (or at least the filename extension).

**Comment by llorllale** [comment]
this is blocking #1238
