### ISSUE TITLE
Introduce - need to lock execution when receiving requests

### ISSUE THREAD

**Issue by soluchok** [hyperledger/aries-framework-go#1284]
Since the protocol support handling messages simultaneously, there is a possibility when two requests might be executed at the same time.
 It might cause a data race. As a result, some of the participants might be lost.
Possible solutions:

1. Get and save participants must be done under the lock or in the same transaction.
2.  If the protocol did not receive the answer (e.g Ack) another message should be sent.

NOTE: The issue might happen when two parallel executions (with the same piID) are trying to execute `saveParticipants` function.
```
md.participants, err = s.getParticipants(md.piID)
if err != nil {
	return fmt.Errorf("getParticipants: %w", err)
}

md.participants = append(md.participants, participant{
	...
})

return s.saveParticipants(md.piID, md.participants)
```

**Comment by llorllale** [comment]
@soluchok is this the cause of [this](https://github.com/hyperledger/aries-framework-go/pull/1291/checks?check_run_id=456776735) failure?

**Comment by soluchok** [comment]
@llorllale  No, it is not. I've added a description.

**Comment by soluchok** [comment]
Done! https://github.com/hyperledger/aries-framework-go/pull/1253
