### ISSUE TITLE
Messaging:  Invitation message for establishing connection

### ISSUE THREAD

**Issue by talwinder50** [hyperledger/aries-framework-go#130]
1. Represent an invitation message for establishing connection
2. Represent connection request message.
3. Represent connection response message.

Reference : https://github.com/hyperledger/aries-cloudagent-python/tree/master/aries_cloudagent/messaging/connections/messages

**Comment by Baha-sk** [comment]
RFC spec: https://github.com/hyperledger/aries-rfcs/tree/master/features/0023-did-exchange

**Comment by talwinder50** [comment]
Not required

**Comment by talwinder50** [comment]
Not required
