### ISSUE TITLE
Controller APIs for VC parsing/encoding

### ISSUE THREAD

**Issue by rolsonquadras** [hyperledger/aries-framework-go#1302]
Build REST/JS Controller APIs for VC Parsing and encoding.

**Comment by troyronda** [comment]
We should also fix the naming conventions of the Go functions (e.g., Parse instead of New where appropriate).

**Comment by rolsonquadras** [comment]
@troyronda created a new issue https://github.com/hyperledger/aries-framework-go/issues/1313 as changing close to 0.1.2 release(end of feb) might break the consumers. We can do this after 0.1.2 release.

**Comment by troyronda** [comment]
Ok. Let's get the naming right in the controller APIs now and then adjust the underlying Go library in 0.1.3.
