### ISSUE TITLE
Manager : Managing the connections

### ISSUE THREAD

**Issue by talwinder50** [hyperledger/aries-framework-go#131]
Things to cover: 
1. Initialize a ConnectionManager.
2. Call the function to Generate new connection invitation.
4. Store the state in the base storage 

Reference: https://github.com/hyperledger/aries-cloudagent-python/tree/master/aries_cloudagent/messaging/connections

**Comment by Baha-sk** [comment]
RFC spec: https://github.com/hyperledger/aries-rfcs/tree/master/features/0023-did-exchange

**Comment by talwinder50** [comment]
Not required

**Comment by talwinder50** [comment]
Not required
