### ISSUE TITLE
Create package to support legacy envelope encryption format

### ISSUE THREAD

**Issue by Moopli** [hyperledger/aries-framework-go#139]
As discussed in [aries-rfcs/issues/133](https://github.com/hyperledger/aries-rfcs/issues/133), implement the 'legacy' crypter from [RFC #0019](https://github.com/hyperledger/aries-rfcs/blob/master/features/0019-encryption-envelope/README.md) in a sibling package to the JWE implementation (#37).

Part of #36 

@Baha-sk

**Comment by Moopli** [comment]
@troyronda Assign me

**Comment by kdenhartog** [comment]
Is the thinking here that we support the legacy non-JWE compliant model? I'd like to say 1.0 is the JWE compliant version we've been discussing and to take the work we've been using and deprecate/no longer support it. What's your thinking on this?

**Comment by troyronda** [comment]
Agree. Our thinking is that 1.0 is the JWE compliant model.
