### ISSUE TITLE
State machine pre/post event handler

### ISSUE THREAD

**Issue by rolsonquadras** [hyperledger/aries-framework-go#140]
Provide support for the consumer of the DID Exchange API to execute logic before/pre and after/post state change.

General idea of this looks something like:
```
type StateHandler interface {
  preState(state, func(ctx) error)
  postState(state, func(ctx) error)
}
```

**Comment by rolsonquadras** [comment]
Part of epic #74

**Comment by fqutishat** [comment]
duplicate #198
