### ISSUE TITLE
Support to customize pack/unpack impl

### ISSUE THREAD

**Issue by rolsonquadras** [hyperledger/aries-framework-go#142]
- Should be able to inject pack/unpack logic
- By default, framework will add NoOp (no pack/unpack)

**Comment by Moopli** [comment]
Injectable pack-unpack was part of #219 

NoOp needs to wait on @fqutishat and @Baha-sk to work out the pack-unpack interface (wallet <-> encrypt/decrypt)

**Comment by troyronda** [comment]
I would think the default for the framework is the JWE compliant pack/unpack?
