### ISSUE TITLE
Suggest: replace api.TransportProviderFactory with anonymous function

### ISSUE THREAD

**Issue by llorllale** [hyperledger/aries-framework-go#143]
I think it would be a good idea for [this option](https://github.com/hyperledger/aries-framework-go/blob/63926ae5866c533021d2fa8831cadc310db08fae/pkg/framework/aries/framework.go#L42-L47) to accept `func() transport.OutboundTransport` instead of defining an [equivalent interface](https://github.com/hyperledger/aries-framework-go/blob/63926ae5866c533021d2fa8831cadc310db08fae/pkg/framework/aries/api/factory.go#L14-L16). I can forsee an explosion of single-method interfaces if we go down this path.

**Comment by troyronda** [comment]
I also think we should avoid such an explosion :).

We should also ensure that options don’t get too fine grained at the framework.
