### ISSUE TITLE
RFC0211: rename: route -> mediate

### ISSUE THREAD

**Issue by llorllale** [hyperledger/aries-framework-go#1448]
updates: https://github.com/hyperledger/aries-rfcs/commit/c36ef7b3b80ae2f6f35c008b18bb2f32bff00345#diff-23f8715937fa369d3a010b4abb01e3f8

**Comment by troyronda** [comment]
Also see https://github.com/hyperledger/aries-rfcs/blob/0b75a4c59d7e33cf0d0e4f292d2425402de94d43/features/0211-route-coordination/README.md

Protocol URI: https://didcomm.org/coordinatemediation/1.0/
