### ISSUE TITLE
ThreadID used instead of ConnectionID in didexchange service

### ISSUE THREAD

**Issue by pfeairheller** [hyperledger/aries-framework-go#1451]
**What I'm trying to do**

Perform a basic DID exchange with peer DIDs between two agents. 

**Expected result**

The connection is established successfully.  Right now the connection is getting abandoned and while trying to diagnose why I am experience a different error in the `abandon` method.

**Actual result**
I enabled debugging and instead of receiving the notification from the abandon method I'm getting the following error in my logs.  Notice how the connection ID changes between the log messages.

```
[aries-framework/did-exchange/service] 2020/03/12 11:48:08 UTC - didexchange.(*Service).handle -> DEBUG persisted the connection record using connection id 0d28c625-6e12-4245-8c33-d850ec29e790
[aries-framework/controller/did-exchange] 2020/03/12 11:48:08 UTC - n/a -> ERROR command=[didexchange] action=[sendConnectionNotification] [connectionID=[35b918ca-7540-4d9d-8bba-2d5552bbea19] stateID=[abandoned]] errMsg=[connection not found]
[aries-framework/controller/did-exchange] 2020/03/12 11:48:08 UTC - didexchange.(*Command).startClientEventListener.func1 -> ERROR handle message events failed : send connection notification failed : connection notification webhook : connection not found
```

Also notice how the "connection ID" in the last message is actually the ThreadID from the connection:
```
{
  "ConnectionID": "0d28c625-6e12-4245-8c33-d850ec29e790",
  "State": "abandoned",
  "ThreadID": "35b918ca-7540-4d9d-8bba-2d5552bbea19",
  "TheirLabel": "agency",
  "TheirDID": "",
  "MyDID": "did:peer:1zQmTzjKsAXD9cqNBLoZsfb3KHvmV9eCxeA1Aw7zttiPyRTj",
  "ServiceEndPoint": "0.0.0.0:6969",
  "RecipientKeys": [
   "5GB73AiBq9ywW6MwaYJYXiLTwatSBtCJFH2iA8cX6Ynn"
  ],
  "InvitationID": "fdc43591-7ec3-4f05-95b1-eebbe9493238",
  "InvitationDID": "",
  "Implicit": false,
  "Namespace": "my"
 }
```

**Sample code / test case**
Notice (at line 490 in pkg/didcomm/protocol/didexchange/service.go) the thread ID is passed to `createErrorEventProperties`:

```	s.sendMsgEvents(&service.StateMsg{
		ProtocolName: DIDExchange,
		Type:         service.PostState,
		Msg:          msg,
		StateID:      stateNameAbandoned,
		Properties:   createErrorEventProperties(thID, "", processErr),
	})
```

And the method signature is asking for the connectionID:

```
func createErrorEventProperties(connectionID, invitationID string, err error) *didExchangeEventError 
```

I believe the fix is simply to change line 490 to pass the connectionID from the `connRec` loaded on line 472:
```
	s.sendMsgEvents(&service.StateMsg{
		ProtocolName: DIDExchange,
		Type:         service.PostState,
		Msg:          msg,
		StateID:      stateNameAbandoned,
		Properties:   createErrorEventProperties(connRec.ConnectionID, "", processErr),
	})

```

I'd be glad to submit a PR if this is correct.

**Comment by llorllale** [comment]
@pfeairheller I agree - `connRec.connectionID` should be passed in there to have the proper logging output. Please submit a PR. Thanks!
