### ISSUE TITLE
Default Storage - Level DB Path configuration

### ISSUE THREAD

**Issue by rolsonquadras** [hyperledger/aries-framework-go#148]
In PR #135, the level DB path is [hardcoded](https://github.com/hyperledger/aries-framework-go/pull/135/files#diff-da8e5280b0328cb616f0b42390a35b00R20). The system should have the ability to set the path dybnamically.

**Comment by llorllale** [comment]
@rolsonquadras moreover, the path should not be set to a global variable.

I suggest initializing a single instance of the store and injecting it to whatever dependencies need it. Note: I'm not suggesting a singleton

**Comment by rolsonquadras** [comment]
The changes have been implemented as part of #208 - [Code Reference](https://github.com/hyperledger/aries-framework-go/pull/208/files#diff-25ff856a2e751abc12ecd949f5fbce50R17)
