### ISSUE TITLE
Deprecated dependency https://github.com/agl/ed25519/

### ISSUE THREAD

**Issue by domwoe** [hyperledger/aries-framework-go#1514]
When trying to use github.com/hyperledger/aries-framework-go/tree/master/pkg/vdri in a go project I'm getting the following error:

> cannot find package "github.com/agl/ed25519/extra25519"

And indeed, https://github.com/agl/ed25519 is unmaintained and not available anymore.

**Comment by Baha-sk** [comment]
I created an issue in Go to hopefully resuscitate the missing functions somewhere official:
https://github.com/golang/go/issues/38074

hopefully these will be moved to Go then we'll update our references 

thanks @domwoe

**Comment by Baha-sk** [comment]
I found an equivalent `extra25519` package in a project that's referenced by Go crypto folks.. this issue will be fixed once my PR is merged.
