### ISSUE TITLE
outofband: Client.CreateRequest() - reenable DID syntax validation

### ISSUE THREAD

**Issue by llorllale** [hyperledger/aries-framework-go#1642]
I had to disable generic syntax validation on the supplied DID while working on #1568 because our sidetree implementation in the BDD tests is creating non-compliant DID IDs.

**Comment by sandrask** [comment]
What is the issue: service ids or actual did id?

**Comment by llorllale** [comment]
@sandrask the actual DID ID is non-compliant

**Comment by llorllale** [comment]
DID syntax validation enabled in PR #2657
