### ISSUE TITLE
return keyID as sha256 string in localkms

### ISSUE THREAD

**Issue by Baha-sk** [hyperledger/aries-framework-go#1680]
currently IDs returned by the new localkms look like this:
`local-lock://custom/master/key/ett5NXovKgRzJDItNY_05tXURi2yL5hHLS_qcXi9zkU=`

kms key can be reduced to 20 bytes and key URI prefix can be omitted.

**Comment by troyronda** [comment]
I assume unpadded Base64URL?

**Comment by Baha-sk** [comment]
> I assume unpadded Base64URL?

yes `base64.RawURLEncoding` @troyronda @fqutishat

**Comment by Baha-sk** [comment]
Following the online discussions, the key returned must be sha256. Updating the issue title to reflect this change..
