### ISSUE TITLE
JSON Web Token proof of Verifiable Credential

### ISSUE THREAD

**Issue by kdimak** [hyperledger/aries-framework-go#173]
Support [JSON Web Token](https://w3c.github.io/vc-data-model/#json-web-token) proof of Verifiable Credential.

**Comment by troyronda** [comment]
> In the DID Auth WG we reconfirmed that ES256K, Ed25519 and RS256 are the algorithms we want to support.

**Comment by troyronda** [comment]
Also see https://github.com/square/go-jose
