### ISSUE TITLE
bug: can't run bdd tests wihtout auth credentials

### ISSUE THREAD

**Issue by AlexeyBelezeko** [hyperledger/aries-framework-go#1734]
**What I'm trying to do**

Run bdd tests on cloned project

**Expected result**

Tests pass successfully

**Actual result**

Tests fails with error:

`
ERROR: Get https://docker.pkg.github.com/v2/trustbloc/sidetree-mock/sidetree/manifests/amd64-0.1.2: no basic auth credentials
make: *** [bdd-test-js] Error 1
`

**Sample code / test case**

`make bdd-test`

**Comment by troyronda** [comment]
github packages currently has a limitation where you need to login, even to read packages.

you can configure your docker client according to: https://help.github.com/en/packages/using-github-packages-with-your-projects-ecosystem/configuring-docker-for-use-with-github-packages#authenticating-to-github-packages

**Comment by AlexeyBelezeko** [comment]
Thanks. My bad.
