### ISSUE TITLE
Implement RecipientKeys in CreateInvitation

### ISSUE THREAD

**Issue by fqutishat** [hyperledger/aries-framework-go#178]
Currently the spec https://github.com/hyperledger/aries-rfcs/tree/master/features/0023-did-exchange#0-invitation-to-exchange don't specify what type of key to generate.

Note: for now will keep it nil

**Comment by llorllale** [comment]
RFC0050 - Wallets: https://github.com/hyperledger/aries-rfcs/tree/master/concepts/0050-wallets
