### ISSUE TITLE
Release v0.1.3

### ISSUE THREAD

**Issue by rolsonquadras** [hyperledger/aries-framework-go#1785]
- Add release notes
- Tag

**Comment by llorllale** [comment]
Support for the [Out-of-Band](https://github.com/hyperledger/aries-rfcs/blob/f0ec8ef7ca396caa56e34e0ab1a808f4d8889c96/features/0434-outofband/README.md) protocols at the SDK level

**Comment by soluchok** [comment]
Added [Issue Credential](https://github.com/hyperledger/aries-rfcs/tree/master/features/0036-issue-credential) and [Present Proof](https://github.com/hyperledger/aries-rfcs/tree/master/features/0037-present-proof) protocols.

**Comment by kdimak** [comment]
Linked Data Signatures:
- Support for JWS proof type.
- Support for `JsonWebSignature2020` and `EcdsaSecp256k1Signature2019` signature suites.

**Comment by aholovko** [comment]
Initial support for [did:key method](https://w3c-ccg.github.io/did-method-key/) in the framework.

**Comment by Baha-sk** [comment]
- New Crypto implementation based on Tink.
- New local KMS implementation using the new Crypto default implementation.
- New ECDH-ES Tink key templates needed for JWE encryption/decryption.
- JWE Serialize/Deserialize support.
- JWE Encrypt/Decrypt support using ECDH-ES Tink key templates
- Support importing private keys into the new local KMS
- Support exporting public keys as raw [ ]byte from local KMS in both DER and IEEE-P1363 format
- Support reading public keys raw [ ]byte as Tink key handles to be used with Crypto/KMS service

**Comment by troyronda** [comment]
@kdimak Is there any summary of the improvements made to VC/VPs that we could mention?

**Comment by kdimak** [comment]
> @kdimak Is there any summary of the improvements made to VC/VPs that we could mention?

@troyronda I can list the following refactoring and bugfix items:
VerifiableCredentials:
- Do not pass private keys directly for signing, use Signer abstraction.
- Support `JsonWebSignature2020` and `EcdsaSecp256k1Signature2019` signature suites.
- Support multiple signature suites for signing and verification.
- Support JWK in the signature suites and in DID resolution.
- Examples of Crypto/KMS based signers and verifiers of VC linked data proofs.
- Improved JSON-LD strict validation of VC / VP documents.

**Comment by rolsonquadras** [comment]
Updated release notes

========================================================
This release adds the following features to the Aries Framework Go.

- Support for the [Out-of-Band](https://github.com/hyperledger/aries-rfcs/blob/f0ec8ef7ca396caa56e34e0ab1a808f4d8889c96/features/0434-outofband/README.md) protocols at the SDK level
- Support for [Issue Credential](https://github.com/hyperledger/aries-rfcs/tree/master/features/0036-issue-credential) and [Present Proof](https://github.com/hyperledger/aries-rfcs/tree/master/features/0037-present-proof) protocols.
- Initial support for [did:key](https://w3c-ccg.github.io/did-method-key/) method in the framework.
- KMS/Crypto
   - New Crypto implementation based on Tink.
   - New local KMS implementation using the new Crypto default implementation.
   - New ECDH-ES Tink key templates needed for JWE encryption/decryption.
   - JWE Serialize/Deserialize support.
   - JWE Encrypt/Decrypt support using ECDH-ES Tink key templates
   - Support importing private keys into the new local KMS
   - Support exporting public keys as raw [ ]byte from local KMS in both DER and IEEE-P1363 format
   - Support reading public keys raw [ ]byte as Tink key handles to be used with Crypto/KMS service
- Linked Data Signatures
  - Support for JWS proof type.
  - Support for JsonWebSignature2020 and EcdsaSecp256k1Signature2019 signature suites.
- VC/VP Improvements
   - Do not pass private keys directly for signing, use Signer abstraction.
   - Support JsonWebSignature2020 and EcdsaSecp256k1Signature2019 signature suites.
   - Support multiple signature suites for signing and verification.
   - Support JWK in the signature suites and in DID resolution.
   - Examples of Crypto/KMS based signers and verifiers of VC linked data proofs.
   - Improved JSON-LD strict validation of VC / VP documents.
========================================================

**Comment by rolsonquadras** [comment]
Aries Framework Go v0.1.3 released -
https://github.com/hyperledger/aries-framework-go/releases/tag/v0.1.3

Docker and NPM v0.1.3 - 
https://github.com/hyperledger/aries-framework-go/packages/69982
https://github.com/hyperledger/aries-framework-go/packages/123279
