### ISSUE TITLE
Adding Proof: deny payload elements outside of the JSON-LD context

### ISSUE THREAD

**Issue by sudeshrshetty** [hyperledger/aries-framework-go#1818]
Currently during signing, we are removing invalid RDF and during verification we are not removing invalid RDFs before calculating digest.

**Change:** Invalid RDF should cause both signing and verification failure. 

Note: invalid RDF detection, filter logic and opts in json ld processor should be left as it is, so that it can be reused by other modules in future.

**Comment by troyronda** [comment]
I think the signing and verification package should provide a consumable warning so that downstream users can decide how to handle this situation. (technically not a failure at the low level package).
