### ISSUE TITLE
Update default endpoint value

### ISSUE THREAD

**Issue by rolsonquadras** [hyperledger/aries-framework-go#1824]
Update the default endpoint for edge agents to https://github.com/hyperledger/aries-rfcs/issues/405#issuecomment-582612875

Ref https://github.com/hyperledger/aries-rfcs/issues/405#issuecomment-581525841

**Comment by troyronda** [comment]
Also see https://github.com/decentralized-identity/didcomm-messaging/pull/49/files#diff-98736ed3e6b7aeab55ce8e164aba8aeaR26
