### ISSUE TITLE
Load protocol services in framework.New()

### ISSUE THREAD

**Issue by rolsonquadras** [hyperledger/aries-framework-go#189]
The framework.Context() returns a [new instance](https://github.com/hyperledger/aries-framework-go/blob/master/pkg/framework/aries/framework.go#L100) of context each time its invoked. Same context should be return whenever Context() is called on same framework instance.

**Comment by rolsonquadras** [comment]
@troyronda @llorllale @fqutishat can you assign this to me and move to in-progress ?

**Comment by llorllale** [comment]
@rolsonquadras is this a bug?

**Comment by rolsonquadras** [comment]
@llorllale yes.

**Comment by rolsonquadras** [comment]
@llorllale as discussed during today's [planning session](https://wiki.hyperledger.org/display/ARIES/2019-09-03+Framework+Go+Weekly+Planning), this is not a bug. But context creation should be done in framework.New() and [loading](https://github.com/hyperledger/aries-framework-go/blob/master/pkg/framework/context/context.go#L37) of protocol services should be moved from context.New() to framework.New().
