### ISSUE TITLE
Invalid didconnection records in store

### ISSUE THREAD

**Issue by sudeshrshetty** [hyperledger/aries-framework-go#1893]
there are few records in didexchange store found with keys likes "

"didconn_%s,%s_did:peer:1zQmTeo7JwEuAjFQ2Rmsnqu9EhWZdqVkiiSpN8dAtLLvbQrA_did:peer:1zQmWeMdrhqy55bMHWEzwHdZfKrBihWvmxBk9ucuPUmBm12b...." which is not correct

**Comment by llorllale** [comment]
@sudeshrshetty can you paste a full example of a connection record?

**Comment by llorllale** [comment]
@sudeshrshetty this was fixed in #1865 .

Are you sure you're using the latest version?

**Comment by sudeshrshetty** [comment]
@llorllale Yes I am using latest version

**Comment by soluchok** [comment]
@llorllale @sudeshrshetty I double-check it.
![Screen Shot 2020-06-05 at 11 13 46 AM](https://user-images.githubusercontent.com/12339578/83853332-cf2dd900-a71d-11ea-9640-5e267fe24978.png)

**Comment by soluchok** [comment]
@sudeshrshetty can we close this issue?

**Comment by llorllale** [comment]
@sudeshrshetty please open another issue if you still find a problem
