### ISSUE TITLE
Unable to get connection of the DidComm message

### ISSUE THREAD

**Issue by rossus** [hyperledger/aries-framework-go#1929]
**What I'm trying to do**

I get issue credential message in an action event. I want to get some info of the connection that send it to me.

**Expected result**

I have a field or method in DidCommMessage or DidCommAction to get connection info .

**Actual result**

I have no way to figure out the connection of the message.

**Comment by llorllale** [comment]
@rossus would providing `myDID`, `theirDID` be enough for your needs?

**Comment by rossus** [comment]
@llorllale yes that would be enough.
