### ISSUE TITLE
build failing: issue credential BDD tests

### ISSUE THREAD

**Issue by llorllale** [hyperledger/aries-framework-go#1980]
https://github.com/hyperledger/aries-framework-go/runs/832397046?check_suite_focus=true

**Comment by soluchok** [comment]
Not sure we can fix it. The issue is related to the timeout` context deadline exceeded`. It happens because of verifiable credentials. We are downloading schema. Which sometimes takes a too long time or even fails. I can increase the timeout will see whether it helps.
