### ISSUE TITLE
Issue Credential Protocol: accepted credentials are saved by credential type as name

### ISSUE THREAD

**Issue by sudeshrshetty** [hyperledger/aries-framework-go#2003]
Current behaviour:
 - Accepted credentials are saved by credential type as name in db ( as db key).

Problems:
- very likely to have db key collision
- can't save multiple credentials of same type (for ex: CreditCardStatement, CrudeProductCredential)
- holder should know the exact type in advance to query it later which doesn't make sense in few scenarios (ex: wallet getting consent credentials from issuer)
- holder is forced to call db twice for getting actual credential (get id by credential name and get credential by ID)

Proposal
- Credentials should be saved by credential ID in db (Note: credential ID is unique and aries vc store uses uuid if credential id is missing)
- accept credential should return id of credential saved, so that holder can retrieve it later (or correlate)

**Comment by soluchok** [comment]
@sudeshrshetty  Credentials are stored under the provided name. If the name is absent then we will use an ID. If ID is absent then we will generate UUID. https://github.com/hyperledger/aries-framework-go/blob/master/pkg/didcomm/protocol/middleware/issuecredential/middlewares.go#L62

Could you please provide the credential you are using?

**Comment by sudeshrshetty** [comment]
thanks @soluchok .
I was unaware that we can pass arbitrary names in request while accepting credentials. 
I will close this issue.
