### ISSUE TITLE
Issue starting OpenAPI demo

### ISSUE THREAD

**Issue by sohee227** [hyperledger/aries-framework-go#2015]
What I'm trying to do

I'm trying to run the OpenAPI demo using
`make run-openapi-demo
`
Actual result
```
hyper@ubuntu:/opt/gopath/src/github.com/did/aries-framework-go$ make run-openapi-demo 
Generating Aries-Framework-Go Test PKI
Signature ok
subject=/C=CA/ST=ON/O=Example Inc.:Aries-Framework-Go/OU=Aries-Framework-Go/CN=*.example.com
Getting CA Private Key
done generating Aries-Framework-Go PKI
Generating and validating controller API specifications using Open API
Generating Open API spec
open /opt/gopath/src/github.com/did/aries-framework-go/build/rest/openapi/spec/openAPI.yml: no such file or directory
Makefile:78: recipe for target 'generate-openapi-spec' failed
make: *** [generate-openapi-spec] Error 1
```

**Comment by Baha-sk** [comment]
@sohee227 I'm noticing in your project path, you're using `/did/`. Can you replace it with `/hyperledger/`?

Also, I would run make all first, to ensure you have a clean successful build.

**Comment by sohee227** [comment]
Thanks for the answer.@Baha-sk 
After replace `/did/` with `/hyperledger/`, I'm trying to run `make all `

![issue_strarting_open_api](https://user-images.githubusercontent.com/30330779/87620608-fa163e80-c759-11ea-9faa-99a9abc64acf.PNG)

However, the results are the same.

**Comment by llorllale** [comment]
@sohee227 PR #2018 was merged as a fix.

Can you confirm it works now for you?

**Comment by sohee227** [comment]
@llorllale I checked it and it works very successfully. Thank.
