### ISSUE TITLE
Update linter to the latest version (golangci)

### ISSUE THREAD

**Issue by soluchok** [hyperledger/aries-framework-go#2032]
https://github.com/golangci/golangci-lint/releases

**Comment by llorllale** [comment]
Someone's going to have fun with `goerr113`

**Comment by ken5scal** [comment]
May I take this issue?

**Comment by soluchok** [comment]
@ken5scal Sure! We would appreciate that.

**Comment by ken5scal** [comment]
@soluchok thanks, I'm gonna start doing it!

**Comment by ken5scal** [comment]
@soluchok Should I just raise the version number in test-suite.yml? or should I fix all the linter reports?

I'm asking because the number of reports is not so small so that they may be not fixed for the historical reasons that I'm not aware of.

**Comment by soluchok** [comment]
@ken5scal ken5scal  Go version is already updated to 1.15. You need to use `golangci-lint 1.31.0`. Better to fix inter reports as much as you can.
If not then just disable the specific linters in `.golangci.yml`. e.g
```
linters:
  disable:
    - testpackage # TODO enable.
```
And leave a TODO to enable it.

**Comment by ken5scal** [comment]
@soluchok great, thanks

**Comment by ken5scal** [comment]
#2181 is done for now.

**Comment by soluchok** [comment]
@ken5scal Thanks.
