### ISSUE TITLE
Issues while running the OpenAPI demo

### ISSUE THREAD

**Issue by anchit93** [hyperledger/aries-framework-go#2056]
I am following the Open API demo and was able to bring up the agents by running `make run-openapi-demo` command however getting below error in the server response while calling `POST /connections/create-invitation` from Alice agent
Error: `TypeError: Failed to fetch`
Not able to debug this as there is no error message logged in the containers running for Alice agent. Same is the case with Bob's agent also.

**Comment by soluchok** [comment]
Could you please describe the steps to reproduce it?
I've checked it `http://localhost:8089/openapi/#/did-exchange/createInvitation` works fine.
Here is a `curl` command. Let me know whether it works.
`curl -X POST "http://localhost:8082/connections/create-invitation?alias=demo" -H "accept: application/json" -d ""`

**Comment by DaevMithran** [comment]
![image](https://user-images.githubusercontent.com/61043607/108964371-661e3500-76a1-11eb-9340-3083d4073a45.png)
I'm trying the open API demo, and getting this error for all APIs in all the Agents

**Comment by soluchok** [comment]
@DaevMithran make sure you are able to open this URL in the browser
https://localhost:8082/connections/create-invitation.
I assume you have a problem with HTTPS. 
Click Advanced->Proceed anyway

**Comment by DaevMithran** [comment]
Yea Thanks!, that was the issue
