### ISSUE TITLE
feat: logging interface and default implementation

### ISSUE THREAD

**Issue by sudeshrshetty** [hyperledger/aries-framework-go#21]
Define generic logging interface for aries framework and provide default implementation.

**Comment by llorllale** [comment]
@sudeshrshetty what do you have in mind?

**Comment by sudeshrshetty** [comment]
//Logger - Standard logger interface
type Logger interface {

	//Fatalf is critical fatal logging, should possibly followed by system shutdown
	Fatalf(msg string, args ...interface{})

	//Panicf is critical logging, should possibly followed by panic
	Panicf(msg string, args ...interface{})

	//Debugf is for logging verbose messages
	Debugf(msg string, args ...interface{})

	//Infof for logging general logging messages
	Infof(msg string, args ...interface{})

	//Warnf is for logging messages about possible issues
	Warnf(msg string, args ...interface{})

	//Errorf is for logging errors
	Errorf(msg string, args ...interface{})
}

Custom implementation can be provided by calling `_logging.Initialize(customProvider)_` before using (before logging any lines).

Logging levels will be maintained by aries framework and it will be module based.
Like, each modules can have their own logging levels enabled.
Default logging level is _INFO_

**Comment by troyronda** [comment]
the discussion here looks useful:

- https://github.com/golang/go/issues/28412
-  https://github.com/golang/go/issues/13182
