### ISSUE TITLE
Receivce Invitation raised "failed from didexchange service handle: threadID not found"

### ISSUE THREAD

**Issue by cyrilhl** [hyperledger/aries-framework-go#2103]
**What I'm trying to do**
- Run "make run-openapi-demo"
- Open Carl agent and Carl router agent
- Create Invitation from Carl router
- Run ReceiveInvitation from Carl

**Expected result**
Connection made on Carl agent and wait for accept invitation

**Actual result**
An Error raised
{"code":2003,"message":"failed from didexchange service handle: threadID not found"}

**Comment by Vid201** [comment]
I had the same problem with receive invitation in Javascript example. There are three fields in created invitation: alias, invitation and invitation_url. When I passed the whole object to receive invitation, I got threadID not found error. Try to pass only invitation property to receive invitation. Worked for me.

**Comment by cyrilhl** [comment]
Yes, my bad. Previously, using program to extract the invitation part. And forget this when manually testing.
Thank you very much.
