### ISSUE TITLE
Update to Go 1.15

### ISSUE THREAD

**Issue by llorllale** [hyperledger/aries-framework-go#2114]
[Go 1.15 is out since yesterday](https://golang.org/doc/go1.15).

- [x] markdown files #2167
- [x] go.mod files #2167
- [x] CI files #2167
- [x] fix build errors below
- [x] update golangci-lint #2032 

Notes:

* ~~golangci-lint is [still on 1.14](https://github.com/golangci/golangci-lint/blob/1844a75eec6cad489133c9d354ddc2e6717f6cc4/build/Dockerfile#L1) so can't yet use new APIs (eg. `testing.T.TempDir()`)~~ [golangci-lint 1.31.0](https://github.com/golangci/golangci-lint/releases/tag/v1.31.0) just released and supports go 1.15
* `make bdd-test` works
* cannot build didexchange nor connection test packages (quick fixes):
```
# github.com/hyperledger/aries-framework-go/pkg/client/didexchange
pkg/client/didexchange/client_test.go:833:19: conversion from int to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
pkg/client/didexchange/client_test.go:881:19: conversion from int to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
FAIL    github.com/hyperledger/aries-framework-go/pkg/client/didexchange [build failed]
...
# github.com/hyperledger/aries-framework-go/pkg/store/connection
pkg/store/connection/connection_lookup_test.go:308:19: conversion from int to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
pkg/store/connection/connection_lookup_test.go:317:19: conversion from int to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
```

**Comment by soluchok** [comment]
I have fixed `conversion from int to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)` error.
