### ISSUE TITLE
Allow injectable Wallet

### ISSUE THREAD

**Issue by fqutishat** [hyperledger/aries-framework-go#213]
- Create Wallet interface
- Allow injectable Wallet

**Comment by fqutishat** [comment]
I propose this wallet interface
@rolsonquadras @llorllale @troyronda @sudeshrshetty 
```
// Wallet interface
type Wallet interface {
	// Open wallet, creating it if so configured.
	// Returns:
	// error: error
	Open() error
	// Close previously-opened wallet, removing it if so configured.
	// Returns:
	// error: error
	Close() error
	// CreateSigningKey create a new public/private signing keypair.
	// Returns:
	// KeyInfo: A `KeyInfo` representing the keypair
	// error: error
	CreateSigningKey(metadata map[string]string) (KeyInfo, error)
	// GetSigningKey Fetch info for a signing keypair.
	// Args:
	// verkey: The verification key of the keypair
	// Returns:
	// KeyInfo: A `KeyInfo` representing the keypair
	// error: error
	GetSigningKey(verKey string) (KeyInfo, error)
	// SignMessage sign a message using the private key associated with a given verification key.
	// Args:
	// message: The message to sign
	// fromVerKey: Sign using the private key related to this verification key
	// Returns:
	// []byte: The signature
	// error: error
	SignMessage(message []byte, fromVerKey string) ([]byte, error)
	// VerifyMessage verify a signature against the public key of the signer.
	// Args:
	// message: The message to verify
	// signature: The signature to verify
	// fromVerKey: Verification key to use in verification
	// Returns:
	// bool: True if verified, else False
	// error: error
	VerifyMessage(message []byte, signature []byte, fromVerKey string) (bool, error)
	// EncryptMessage encrypt message
	// Args:
	// message: The binary message content
	// toVerKey: The verification key of the recipient
	// fromVerKey: The verification key of the sender
	// Returns:
	// []byte: The encrypted message content
	// error: error
	EncryptMessage(message []byte, toVerKey, fromVerKey string) ([]byte, error)
	// DecryptMessage decrypt message
	// Args:
	// encMessage: The encrypted message content
	// toVerKey:The verification key of the recipient.
	// []byte: Decrypted message content
	// string: The sender verification key
	// error: error
	DecryptMessage(encMessage []byte, toVerKey string) ([]byte, string, error)
	// PackMessage Pack a message for one or more recipients.
	// Args:
	// message: The message to pack
	// toVerKeys: The verification keys to pack the message for
	// fromVerKey: The sender verification key
	// Returns:
	// []byte: The packed message
	// error: error
	PackMessage(message []byte, toVerKeys []string, fromVerKey string) ([]byte, error)
	// Unpack a message.
	// Args:
	// encMessage: The encrypted message
	// Returns:
	// string: message
	// string: fromVerKey
	// string: toVerKeys
	// error: error
	UnpackMessage(encMessage []byte) (string, string, string, error)
}

// KeyInfo contains public and private key
type KeyInfo interface {
	GetVerification() string
	GetMetadata() map[string]string
}
```

**Comment by fqutishat** [comment]
https://github.com/hyperledger/aries-cloudagent-python/blob/master/aries_cloudagent/wallet/base.py

**Comment by llorllale** [comment]
If we are to follow the principles of [Managing Secrets](https://github.com/hyperledger/aries-rfcs/blob/master/concepts/0050-wallets/README.md#managing-secrets):

* it makes sense to have this fat interface for wallets
* `KeyInfo` must **not** expose private keys at all. Secrets **never** leave the wallet.

Having said that:

* What is the difference between `EncryptMessage`/`DecryptMessage` and the `Pack`/`Unpack` methods?
* What goes in the key metadata map?
* I'm not sure of the need for `GetSigningKey`. If `CreateSigningKey` returns the `verKey` then I can pass that to `SignMessage` without having to call GetSigningKey.
* I don't see why `VerifyMessage` needs to be part of the Wallet.

**Comment by llorllale** [comment]
Funny question: do we even need different wallet implementations? We already support injectable storage.

**Comment by Baha-sk** [comment]
@garisty @firas.qutishat EncryptMessage() should encrypt a message for a single recipient, according to the python docs, it deals with Authcrypt vs Anoncrypt encryption based on wether the sender key is passed in as an argument... while Pack() takes a list of recipients.. ( I guess pack can call EncryptMessage for each recipient )  and packs a JWE envelope to be sent over the wire... now the question remain.. do we want to expose EncryptMessage() in the interface.. we will find out as we implement more features for the agents..

**Comment by fqutishat** [comment]
@llorllale @troyronda 

What is the difference between EncryptMessage/DecryptMessage and the Pack/Unpack methods?
https://github.com/hyperledger/aries-framework-go/issues/213#issuecomment-528892756

What goes in the key metadata map?
info about the key like keyType

I'm not sure of the need for GetSigningKey. If CreateSigningKey returns the verKey then I can pass that to SignMessage without having to call GetSigningKey?
you need GetSigningKey to retrieve key metadata 

I don't see why VerifyMessage needs to be part of the Wallet?
The VerifyMessage need private key to verify signature and private key not suppose to be outside the Wallet

**Comment by troyronda** [comment]
@Baha-sk Is Pack/Unpack strictly a superset of Encrypt/Decrypt?

**Comment by rolsonquadras** [comment]
> // KeyInfo contains public and private key
> type KeyInfo interface {
> 	GetVerification() string
> 	GetMetadata() map[string]string
> }
@fqutishat what would GetVerification() return? Is it verification/public key ?
