### ISSUE TITLE
did.Doc should implement json.Marshaler

### ISSUE THREAD

**Issue by llorllale** [hyperledger/aries-framework-go#2149]
Users typically expect `json.Marshal(didDoc)` to produce a correctly formatted did document but that is not the case. Users are not typically aware of `did.Doc.JSONBytes()`. 

We should implement `MarshalJSON()` to avoid surprises.

**Comment by gnarula** [comment]
There's more to it than an enhancement I believe. There's an interop issue with didexchange's Response message. The `did_doc` is marshalled to the `did.Doc` struct which has the field names beginning with an uppercase alphabet. Besides, I'm not sure if direct marshalling of the struct even results in a valid did doc that can be shared with other agents.

**Comment by llorllale** [comment]
@gnarula 

> There's more to it than an enhancement I believe. There's an interop issue with didexchange's Response message. The `did_doc` is marshalled to the `did.Doc` struct which has the field names beginning with an uppercase alphabet. 

Absolutely correct - we are doing didexchange.Response wrong. I was holding off on this until we got around to #1826 TBH.

> Besides, I'm not sure if direct marshalling of the struct even results in a valid did doc that can be shared with other agents.

Yes. This seems to be a method-specific thing. Example: the genesis version of `did:peer` cannot be sent with a simple serialization of `did.Doc` because you'd also need to strip out the DID subject.
