### ISSUE TITLE
Abstraction issue: JWE Encrypter code should be independent from DIDComm

### ISSUE THREAD

**Issue by DRK3** [hyperledger/aries-framework-go#2153]
In the composite package, there's an encryption type called "DIDCommEncType", but the JWE encryption code should not have any DIDComm-specific stuff in there. It becomes a problem for other projects which use the JWE encrypter, since now they are forced to have a reference to DIDComm which may or may not make sense to be in that project.

**Comment by DRK3** [comment]
@fqutishat @llorllale can you assign to @Baha-sk

**Comment by Baha-sk** [comment]
JWEEncrypter depends on the packer service that builds the JWE envelope. Currently the framework supports 3 types: legacy (authcrypt) packer, (new) authcrypt packer and (new) anoncrypt packer.

These build JWE envelopes specifically for didComm using specific protected `typ` header values. This header value (along with the new skid header field) determine what packer to use for building the envelope. One can use another library or create another custom packer implementation with new `typ` value. 

For now, JWEEncrypter will be limited to the current packer implementations in aries-farmework-go which means the protected header `typ` value should be `didcomm-envelope-enc` for the new packers or `JWM/1.0`  for the legacy one.

closing this issue as there is nothing to be done in Aries-framework-go.
