### ISSUE TITLE
OpenAPI demo - CORS policy error

### ISSUE THREAD

**Issue by Vid201** [hyperledger/aries-framework-go#2186]
**What I'm trying to do**

Create invitation on Swagger interface for Alice's agent.

**Expected result**

Invitation created and shown on Swagger interface.

**Actual result**

Request to Alice's agent is blocked (console: Access to fetch at 'http://localhost:9082/connections/create-invitation' from origin 'http://localhost:9089' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.)

**Extra**

This is not working on the latest commit, I know it worked some time ago.

**Comment by soluchok** [comment]
@Vid201 You need to choose HTTPS schema in swagger UI.
