### ISSUE TITLE
CouchDB: add support for key that starts with underscore

### ISSUE THREAD

**Issue by soluchok** [hyperledger/aries-framework-go#2191]
Currently, we are not able to use keys that start with an underscore. e.g `_somekey`.
CouchDB will raise an error `Only reserved document ids may start with underscore`.
This is a big problem for us. For example in `KMS`implementation we have something like this 
`base64.RawURLEncoding.EncodeToString(random.GetRandomBytes(uint32(keySetIDLength)))`
Since _ (underscore) is a character that can be used for base64 there is no guarantee that `_ ` will not be the first character.

Requirements:
The problem should be resolved in CouchDB implementation.

**Comment by Baha-sk** [comment]
this is duplicate of #2137

currently the framework has base58Wrapper to fix this, it will be replaced with prefixWrapper soon (upcoming PR I'm working on)
