### ISSUE TITLE
Doc Storage - Interface design

### ISSUE THREAD

**Issue by rolsonquadras** [hyperledger/aries-framework-go#22]
The Aries Framework should support pluggable storage(e.g file store, embedded db store, cloud store, etc.) for DID documents along with Connections(pairwise mapping).

**Comment by llorllale** [comment]
@rolsonquadras agreed

These are the key things an Agent needs to do:

1. Store pairwise mappings of DIDs (ours and theirs)
2. Look up a pairwise mapping of DIDs from just the sender's public key (when receiving a message)
3. Look up pairwise mappings in order to then send a message to the other party.

Rough draft:
```go
package did

// Connection is a pairwise relation between two DIDs (ours and theirs)
type Connection struct {
   Mine *did.Doc
   Theirs *did.Doc
   Label string // human readable string set by the user, such as "Bob"
}

// Store is the storage interface for DIDs
type Store interface {
    Iter() *Iterator  // <--- iterator of Connections
    Put(c *Connection) error
    LookupByTheirPublicKey(k crypto.PublicKey) (c *Connection, found bool)
}
```

**Comment by rolsonquadras** [comment]
@llorllale Based on our offline discussion, i have updated interface design. 

docstore to store only peer did docs
```
package docstore

type Store interface {
	// Put stores the DID Doc
	Put(*did.Doc) error

	// GetAll fetches the DID Doc based on DID
	Get(string) (*did.Doc, error)

	// GetAll fetches all the DID Docs
	Iter() *DocIterator
}
```

connstore to store the mapping between my DID and their DID along with their public key
```
package connstore

// Connection is a pairwise relation between two DIDs (ours and theirs)
type Connection struct {
	MineDID        string
	TheirDID       string
	TheirPublicKey []byte
	Label          string
}

type Store interface {
	Iter() *ConnIterator // <--- iterator of Connections
	Put(c *Connection) error
	LookupByTheirPublicKey(pubKey *[]byte) (*Connection, bool)
}
```

Primary consideration to have separate the doc store from connection store is to have a clear scope for each items rather than mixing both, which might result in maintainability issues later on. Also, peer did resolution will be simpler with a separate DID Doc store as we can just pass the DID to the method.

Please Let me know your thoughts. @troyronda FYI.

**Comment by llorllale** [comment]
@rolsonquadras sounds good
