### ISSUE TITLE
Remove phoreproject/bls dependency

### ISSUE THREAD

**Issue by kdimak** [hyperledger/aries-framework-go#2248]
We use `Fr` type from [phoreproject/bls](github.com/phoreproject/bls) to implement BBS+, it's missing in [kilic/bls12-381](github.com/kilic/bls12-381)
@mikelodder7 said that we can use math.big mod Q (from G1.Q).

**Comment by kilic** [comment]
`Fr` type is now implemented in kilic/bls12-381

**Comment by llorllale** [comment]
Thank you @kilic !

**Comment by kdimak** [comment]
Hi @kilic ! Thank you for implementing `Fr` type. I almost completed the migration from `phoreproject/bls` to `kilic/bls12-381`. One thing missing I see for now is `Fr.Inverse()`. Could you help us with this? I tried to implement this myself taking `inverse(inv, e *fe)` as a reference but did not succeed.

**Comment by kilic** [comment]
https://github.com/kilic/bls12-381/blob/a288617c07f1bd60613c43dbde211b4a911e4791/fr.go#L257

We have it now.

**Comment by kdimak** [comment]
> https://github.com/kilic/bls12-381/blob/a288617c07f1bd60613c43dbde211b4a911e4791/fr.go#L257
> 
> @kdimak, we have it now.

Superb! I've just checked it, works like a charm. Thank you indeed @kilic !
