### ISSUE TITLE
DID Exchange - Persist connections

### ISSUE THREAD

**Issue by sudeshrshetty** [hyperledger/aries-framework-go#226]
Part of epic #42 

To be able to query connection invitations from controller and client.

**Comment by fqutishat** [comment]
save invitations inside storage

**Comment by sudeshrshetty** [comment]
Also should be able to remove invitations from storage (by ID)

**Comment by llorllale** [comment]
@fqutishat @sudeshrshetty which component should save the invitations, and to what storage?

Note: the did-exchange state machine will eventually use the Wallet. I don't think wallets are a mechanism for storing historical data.

**Comment by llorllale** [comment]
@sudeshrshetty the meaning of "wallet" is a bit more broader than that - and is still in flux (see the ongoing discussion on hyperledger/aries-rfcs#68 for example).

My point is that a "wallet" stores more than just keys - it stores PII, of which keys is a subset. DIDs and VCs are PII.

**Comment by sandrask** [comment]
Invitee generates connection record during create invitation with generated thread id
and store recipientKeys and serviceEndpoint in it. Then inviter creates new did for exchange request and stores it to connection record. 
Inviter generates connection record with thread id when receiving exchange request and stores his invitation public key id and  invitee did into connection record. Then inviter creates new did for exchange response and updates connection record with it. 

```Connection record is stored as a json document and it contains at least the following:
thread_id
id
my_did
their_did
their_label
state```




type ConnectionRecord struct {}
