### ISSUE TITLE
outofband updates

### ISSUE THREAD

**Issue by llorllale** [hyperledger/aries-framework-go#2283]
Need to support the latest changes to the outofband RFC, particularly [reuse](https://github.com/hyperledger/aries-rfcs/blob/master/features/0434-outofband/README.md#reuse-httpsdidcommorgout-of-bandverhandshake-reuse)

- [x] delete `request`
- [x] ensure `invitation` matches the schema
- [x] verify if good to refactor some logic around defaults in order to align with RFC. Example: we are always including `handshake_protocols` in the outgoing invitation
- [x] support `handshake-reuse` and `handshake-reuse-accepted` PR #2729 
- [x] add `accept` property once this is merged: https://github.com/hyperledger/aries-rfcs/pull/595

**Comment by pfeairheller** [comment]
Several changes are needed to support the current version of  [spec](https://github.com/hyperledger/aries-rfcs/blob/master/features/0434-outofband/README.md). 

The latest version has changed the message type to `https://didcomm.org/out-of-band/%VER`.

There is now only one message for the protocol: `https://didcomm.org/out-of-band/%VER/invitation`.

The invitation message has both `handshake_protocols` (renamed from `protocols`) and `request~attach` along with the `service` fields with a set of rules for how the framework [should handle](https://github.com/hyperledger/aries-rfcs/blob/master/features/0434-outofband/README.md#responses) the existence of those fields relative to one another.

Also not sure of the current support in the framework for ephemeral connections but this protocol is designed to support that feature by allowing for using the `service` items to drive connectionless protocols.

**Comment by llorllale** [comment]
@pfeairheller we just released [v0.1.5](https://github.com/hyperledger/aries-framework-go/releases/tag/v0.1.5). Now would be a good time to pick this one up, if you are interested.

**Comment by pfeairheller** [comment]
> @pfeairheller we just released [v0.1.5](https://github.com/hyperledger/aries-framework-go/releases/tag/v0.1.5). Now would be a good time to pick this one up, if you are interested.

@m00sey and @mikaelaTar will be picking this up after they push #626
