### ISSUE TITLE
did:key - support P256

### ISSUE THREAD

**Issue by llorllale** [hyperledger/aries-framework-go#2319]
The `did:key` VDR should support the P-256 curve. [`JsonWebKey2020`](https://www.w3.org/TR/did-spec-registries/#jsonwebkey2020) can be used as the verification method's `type`.

More on JsonWebKey2020: https://w3c-ccg.github.io/lds-jws2020/#json-web-key-2020

Note: method-specific ID considerations: https://w3c-ccg.github.io/did-method-key/#p-256

Here's a test vector for P-256: https://github.com/w3c-ccg/did-method-key/blob/master/test-vectors/nist-curves.json#L2

**Comment by troyronda** [comment]
Should also support the other P curves.

**Comment by Baha-sk** [comment]
> The `did:key` VDR should support the P-256 curve. [`JsonWebKey2020`](https://www.w3.org/TR/did-spec-registries/#jsonwebkey2020) can be used as the verification method's `type`.
> 
> More on JsonWebKey2020: https://w3c-ccg.github.io/lds-jws2020/#json-web-key-2020
> 
> Note: method-specific ID considerations: https://w3c-ccg.github.io/did-method-key/#p-256
> 
> Here's a test vector for P-256: https://github.com/w3c-ccg/did-method-key/blob/d50497be6a75c0d44b83c2340339e48c4d734ceb/test-vectors/nist-curves.json#L2

the nist-curves test vector link should be updated to :
https://github.com/w3c-ccg/did-method-key/blob/master/test-vectors/nist-curves.json#L2
the link in the issue is outdated

**Comment by llorllale** [comment]
@Baha-sk done
