### ISSUE TITLE
Implement support for reading key content from a file in a standard format

### ISSUE THREAD

**Issue by aholovko** [hyperledger/aries-framework-go#2346]
Currently `local.MasterKeyFromPath(path string)` supports files with key content in raw bytes. It should support files in standard format (e.g. PEM or DER).

**Comment by aholovko** [comment]
Keys used for secret locks in KMS are symmetric ones. They are just random byte arrays that should be stored in a file without any structure. @Baha-sk I suggest closing this issue. Let me know what you think about this. Thanks.

**Comment by Baha-sk** [comment]
that's ok, you can close it for now @aholovko
