### ISSUE TITLE
DID Exchange - Service handle for Accept Request

### ISSUE THREAD

**Issue by sudeshrshetty** [hyperledger/aries-framework-go#238]
Part of epic #42

Rest API and Client SDK will call didexchange service handle to accept DID exchange request (By ID).

- Service should look for stored exchange request and accept it (state update)
- Service should perform outbound - send exchange response
- Service should call post event listeners so that client/REST API can get proper response

**Comment by llorllale** [comment]
@sudeshrshetty 
 
> Rest API and Client SDK will call didexchange service handle to accept DID exchange request (By ID).

What do you mean "by ID"? ID of what?

**Comment by fqutishat** [comment]
@sudeshrshetty need to re-grooming
