### ISSUE TITLE
Create package for Linked Data Signatures

### ISSUE THREAD

**Issue by Moopli** [hyperledger/aries-framework-go#241]
For signing DID documents we need an implementation of [Linked Data Signatures](https://w3c-dvcg.github.io/ld-signatures/) for DID documents. Linked Data Signatures can be applied to any JSON-LD structure, but we only need them for DID documents and can rely on DID document specifics like the public key.

For signing a document, we need:
- A JSON struct for:
  - A JSON-LD document (DID document)
  - A signature verification key
- An interface for a Signature Suite, providing implementations of the [3 algorithms](https://w3c-dvcg.github.io/ld-signatures/#signature-suites) expected.
- External API for signing a document and verifying a signature, given the document, suite, and verification key
- Internal functions:
  - [Create Verify Hash Algorithm](https://w3c-dvcg.github.io/ld-signatures/#create-verify-hash-algorithm) is used by both Sign and Verify

For this issue create the interfaces, stub implementation, structs, stub APIs, so different parts of the implementation don't completely block each other.

Part of #96

**Comment by sandrask** [comment]
Implemented in above mentioned issues

**Comment by Moopli** [comment]
Done!
