### ISSUE TITLE
Implement Linked Data Signature Create Verify Hash Algorithm

### ISSUE THREAD

**Issue by Moopli** [hyperledger/aries-framework-go#243]
Linked Data signatures use the [Create Verify Hash Algorithm](https://w3c-dvcg.github.io/ld-signatures/#create-verify-hash-algorithm) as part of both the Signing algorithm and the Verification algorithm. Implement the algorithm, given the parameters listed in the spec, where it calls the canonicalization algorithm and message digest algorithm provided by the Signature Suite.

Part of #96

**Comment by sandrask** [comment]
Depends on #241
