### ISSUE TITLE
Implement Linked Data Signing Algorithm

### ISSUE THREAD

**Issue by Moopli** [hyperledger/aries-framework-go#244]
Linked Data documents (including DIDs) are signed via [this algorithm](https://w3c-dvcg.github.io/ld-signatures/#signature-algorithm). This manipulates and canonicalizes the document, calls the Create Verify Hash Algorithm (implemented in #243), calls the signing algorithm provided by the given Signature Suite, and adds the signature to the document.

Part of #96

**Comment by Moopli** [comment]
Note that the spec may be inconsistent (being under review), it occasionally mentions a `signature` key in the document, instead we now use the `proof` and `proofChain` keys.

**Comment by sandrask** [comment]
Depends on #241

**Comment by sandrask** [comment]
Depends on #243
