### ISSUE TITLE
Implement Linked Data Signature Verification Algorithm

### ISSUE THREAD

**Issue by Moopli** [hyperledger/aries-framework-go#245]
Linked Data document signatures are verified using [this algorithm](https://w3c-dvcg.github.io/ld-signatures/#signature-verification-algorithm). Fetch and verify the public key in the signature, manipulate and canonicalize a copy of the document, call the Create Verify Hash Algorithm (implemented in #243), and verify the result using the signature algorithm.

Part of #96

**Comment by Moopli** [comment]
Note that the spec may be inconsistent (being under review), it occasionally mentions a `signature` key in the document, instead we now use the `proof` and `proofChain` keys.

**Comment by sandrask** [comment]
Depends on #241
