### ISSUE TITLE
Controller API : add missing endpoints and validate spec

### ISSUE THREAD

**Issue by sudeshrshetty** [hyperledger/aries-framework-go#247]
Related to epic #95 

- add validate spec makefile target in aries-framework-go
- add missing endpoints like remove connection etc

**Comment by llorllale** [comment]
@sudeshrshetty what is a "spec target"?

**Comment by sudeshrshetty** [comment]
All restapi pkg functions and models are now following open API annotation specifications, this target will generate spec and validate to find any discrepancies.
Once this make file target is in place, anyone is free to update any restapi models or functions, this target will make sure that open API specification is followed. In future, we are going to use this spec for docs and tests.
