### ISSUE TITLE
Implement Ed25519VerificationKey2018 Linked Data Signature Suite

### ISSUE THREAD

**Issue by Moopli** [hyperledger/aries-framework-go#248]
In #241 we create an interface for a generic pluggable Linked Data Signature Suite. Here we create an implementation of the [Ed25519 2018](https://w3c-dvcg.github.io/lds-ed25519-2018/) signature suite, so Sign and Verify can be done using `Ed25519VerificationKey2018`.

Part of #96

**Comment by sandrask** [comment]
Depends on #241
