### ISSUE TITLE
When I try do a make fail 

### ISSUE THREAD

**Issue by welbert6** [hyperledger/aries-framework-go#2649]
**What I'm trying to do**

I'm trying generate a .aar and when I do a 'make all' fail with the system cannot find the path specified
*** [clean-android] Error 2
<img width="855" alt="Screenshot_5" src="https://user-images.githubusercontent.com/23161715/111469656-b4a17b00-8705-11eb-82aa-092f34af3a8c.png">

**Comment by troyronda** [comment]
@welbertim We haven't tested the build on Windows. You can use Linux or Mac to do the build.

**Comment by welbertim** [comment]
Thank you
