### ISSUE TITLE
RFC 0028: Introduce Protocol

### ISSUE THREAD

**Issue by llorllale** [hyperledger/aries-framework-go#269]
Add support for the [`introduce`](https://github.com/hyperledger/aries-rfcs/blob/master/features/0028-introduce/README.md) protocol.

Should follow the same overall design as the existing did-exchange state machine: https://github.com/hyperledger/aries-framework-go/tree/master/pkg/didcomm/protocol/didexchange

**Comment by troyronda** [comment]
Basic support for Introduce is now enabled. #882 lists additional TODO items.
