### ISSUE TITLE
VC Wallet: EDV support

### ISSUE THREAD

**Issue by sudeshrshetty** [hyperledger/aries-framework-go#2745]
Note: current Aries [EDV storage provider](https://github.com/hyperledger/aries-framework-go/blob/main/component/storage/edv/restprovider.go#L89) supports only one vault. Calling OpenStore(name)  just adds dbnamespace.

Here is the plan to integrate aries wallet with EDV: 
**_PLAN A_**
- As per existing behaviour, wallet implementation will expect StorageProvider during [initialization](https://github.com/hyperledger/aries-framework-go/blob/main/pkg/wallet/wallet.go#L94). For EDV users, it will be client's responsibility to pass right storage provider. (in case of REST, command controller's responsibility )

**_PLAN B_**
- During profile creation wallet will expect EDVServerURL & VaultID options to use EDV as content storage.
- VCWallet will create its own EDV provider instance ([using this](https://github.com/hyperledger/aries-framework-go/blob/main/component/storage/edv/restprovider.go#L89)  ) internally for that user.
- Wallet will open store during unlock (for all storage provider types) and close store during lock.
- EDV will use wallet profile KMS options as EDV encrypter

**Comment by troyronda** [comment]
I think there should be a package that implements the Plan B mechanism.
An instance of that package is then passed into the initializer as a StorageProvider (similar to the mechanism mentioned in Plan A).

i.e., wallet package should not be hard-coded to the Plan B mechanism - rather "Plan B" is injected.
@sudeshrshetty

**Comment by sudeshrshetty** [comment]
Yes, PLAN B will fall back to PLAN A if EDV opts are not found in wallet profile.
