### ISSUE TITLE
Cannot read data for imported key - failed to get DB entry: data not found

### ISSUE THREAD

**Issue by Vid201** [hyperledger/aries-framework-go#2791]
**What I'm trying to do**

Sign credential with `did:key:z6Mkf3mSeHmehoXVdXQt1uNimKxD9RqFXHS6EgbVaDx4B5Z5`.

**Expected result**

Given credential signed - added proof field.

**Actual result**

{"code":6011,"message":"sign credential : getKeySet: failed to read json keyset from reader: cannot read data for keysetID z6Mkf3mSeHmehoXVdXQt1uNimKxD9RqFXHS6EgbVaDx4B5Z5: failed to get DB entry: data not found"}

**Sample code / test case**

I am trying to sign credential (/verifiable/signcredential) with method did:key. First I import private keys. If I do: `curl -k -X 'POST' 'https://localhost:8082/kms/import' -H 'accept: application/json' -d '{"kty": "OKP", "kid":"z6Mkf3mSeHmehoXVdXQt1uNimKxD9RqFXHS6EgbVaDx4B5Z5", "crv": "Ed25519", "x": "CNb8wOgK85fU-llKCe-vjohzqJjNR3E2O83ROzsOF3Q", "d": "ljk-imkUm6nJzP32ucxjog3dg1lDO0JoYvx-pbxV4oM"}'`  (this private key in JWK format correspond to the mentioned did:key), I get response `{}` (they are successfully imported). If I run the same command again, I get `{"code":7002,"message":"import private EC key failed: writeToStore: failed to write buffer to store: requested ID 'z6Mkf3mSeHmehoXVdXQt1uNimKxD9RqFXHS6EgbVaDx4B5Z5' already exists, cannot write keyset"}` - looks okay.

But when I call sign credential endpoint with `curl -k -X POST "https://localhost:9082/verifiable/signcredential" -H  "accept: application/json" -H  "Content-Type: application/json" -d "{  \"created\": \"2021-05-05T10:22:25.999Z\",  \"credential\": {                  \"@context\":[                     \"https://www.w3.org/2018/credentials/v1\",                     \"https://www.w3.org/2018/credentials/examples/v1\"                  ],                  \"credentialSubject\":{                     \"id\":\"sample-credential-subject-id\"                  },                  \"id\":\"http://example.edu/credentials/1872\",                  \"issuanceDate\":\"2010-01-01T19:23:24Z\",                  \"issuer\":{                     \"id\":\"did:example:09s12ec712ebc6f1c671ebfeb1f\",                     \"name\":\"Example University\"                  },                  \"referenceNumber\":83294847,                  \"type\":[                     \"VerifiableCredential\",                     \"UniversityDegreeCredential\"                  ]               },  \"did\": \"did:key:z6Mkf3mSeHmehoXVdXQt1uNimKxD9RqFXHS6EgbVaDx4B5Z5\",  \"signatureType\": \"Ed25519Signature2018\"       }" `, it returns `{"code":6011,"message":"sign credential : getKeySet: failed to read json keyset from reader: cannot read data for keysetID z6Mkf3mSeHmehoXVdXQt1uNimKxD9RqFXHS6EgbVaDx4B5Z5: failed to get DB entry: data not found"}`.

Not sure if I am importing keys in the wrong way or there is a bug.

**Comment by sudeshrshetty** [comment]
@Vid201 I tried your steps and it worked for me.

As I can see you are importing keys into one agent and trying to sign credential from another :)

Below command works just fine
```
curl -X 'POST' \
  'https://localhost:8082/verifiable/signcredential' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
 
  "credential": {
      "@context": [
        "https://www.w3.org/2018/credentials/v1",
        "https://www.w3.org/2018/credentials/examples/v1",
		"https://w3id.org/security/bbs/v1"
      ],
     "credentialSchema": [],
      "credentialSubject": {
        "degree": {
          "type": "BachelorDegree",
          "university": "MIT"
        },
        "id": "did:example:ebfeb1f712ebc6f1c276e12ec21",
        "name": "Jayden Doe",
        "spouse": "did:example:c276e12ec21ebfeb1f712ebc6f1"
      },
      "expirationDate": "2020-01-01T19:23:24Z",
      "id": "http://example.edu/credentials/1872",
      "issuanceDate": "2010-01-01T19:23:24Z",
      "issuer": {
        "id": "did:example:76e12ec712ebc6f1c221ebfeb1f",
        "name": "Example University"
      },
      "referenceNumber": 83294847,
      "type": [
        "VerifiableCredential",
        "UniversityDegreeCredential"
      ]
    },
  "did": "did:key:z6Mkf3mSeHmehoXVdXQt1uNimKxD9RqFXHS6EgbVaDx4B5Z5",
"signatureType":"Ed25519Signature2018"
  
}'

```

**Comment by Vid201** [comment]
@sudeshrshetty You are completely right, it works, thanks for pointing out. Can't believe did not see that. :)

**Comment by fastman61** [comment]
@sudeshrshetty  When I am trying this call, it gives that error. Because there is a hardcoded context URI on prepareJWSProof function on jws.go. When add "https://w3id.org/security/bbs/v1" instead of "https://w3id.org/security/jws/v1", it seems working. How can I use BbsBlsSignature2020 for signing?
```
	// TODO proof contexts shouldn't be hardcoded in jws, should be passed in jsonld doc by author [Issue#1833]
	proofOptions[jsonldContext] = []interface{}{securityContext, securityContextJWK2020}
```
```
curl -X 'POST' \
  'https://localhost:8082/verifiable/signcredential' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
    "credential": {
        "@context": [
            "https://www.w3.org/2018/credentials/v1",
            "https://w3id.org/citizenship/v1"
        ],
        "credentialSubject": {
            "birthCountry": "Bahamas",
            "birthDate": "1958-07-17",
            "familyName": "SMITH",
            "gender": "Female",
            "givenName": "ALICE",
            "type": [
                "PermanentResident"
            ]
        },
        "id": "https://credential.example.com/residents/1234567890",
        "issuanceDate": "2020-01-01T12:00:00Z",
        "issuer": "did:key:zUC75bB6JA9GjDAyZJjZsoynhQuoSmzK2299chH2spjtwnsB9CNLZSA4LJhpmno2z3MyPuWqKY1fBhF3YYe8CczEej4fGo5SrgD9XgjzPGiF3uLB2Wf2DVEtC85rYW9Ru67PNTN",
        "proof": {
            "created": "2022-12-17T17:25:26.235583009Z",
            "proofPurpose": "assertionMethod",
            "proofValue": "qxP8z6vNYRvaetwaEU8hZb5MJ4EMH7FFj_D6fhtrxpNoTwTexkWbPNGkk16IFftQRQ0UHqdFoOtBQ15jXR_ydJ7W4ArI-IUnNUmf252iFTU4yczZbBSCVO4a7mQbFuR4ssc76bmfWoag0GpDS0N6LA",
            "type": "BbsBlsSignature2020",
            "verificationMethod": "did:key:zUC75bB6JA9GjDAyZJjZsoynhQuoSmzK2299chH2spjtwnsB9CNLZSA4LJhpmno2z3MyPuWqKY1fBhF3YYe8CczEej4fGo5SrgD9XgjzPGiF3uLB2Wf2DVEtC85rYW9Ru67PNTN#zUC75bB6JA9GjDAyZJjZsoynhQuoSmzK2299chH2spjtwnsB9CNLZSA4LJhpmno2z3MyPuWqKY1fBhF3YYe8CczEej4fGo5SrgD9XgjzPGiF3uLB2Wf2DVEtC85rYW9Ru67PNTN"
        },
        "type": [
            "VerifiableCredential",
            "PermanentResident"
        ]
    },
    "did": "did:key:zUC74hLbUrGUFKyVb3ehRU3rvpeb7HVYrCEQsbki5B18r5K4X2iKxBgygjbLstfLa7ZNLoQrsWxUcNJpjSBD5fDbXgyrm9opUPieU6dP98HGg1uKhq4yUNCq8gp4a363BzVUEcx",
    "kid": "lj5wm6xAkoILabkidOgAYzG4ApvTMvfm38WVYztK_Us",
    "signatureType": "BbsBlsSignature2020"
}'
```
**Error:** 
```
{
    "code": 6011,
    "message": "sign credential : failed to add linked data proof: add linked data proof: invalid JSON-LD context"
}
```

**Comment by sezer** [comment]
Same here.  Any comment about this?
