### ISSUE TITLE
Cannot Build Android Bindings

### ISSUE THREAD

**Issue by Marco77577** [hyperledger/aries-framework-go#2890]
**What I'm trying to do**

I am trying to build the Android bindings aar according to the guide (https://github.com/hyperledger/aries-framework-go/tree/main/cmd/aries-agent-mobile).

I installed go, gomobile, set up Android Studio and the two environment variables.

**Expected result**

When I run make bindings-android, I expect to get the aar built.

**Actual result**

The actual result is (after installing all go dependencies) this:
```bash
gomobile: go build -v -ldflags -s -w -buildmode=c-shared -o=/var/folders/pl/m3mpk9855fl98dh7780lplcmtfhfkt/T/gomobile-work-882664003/android/src/main/jniLibs/armeabi-v7a/libgojni.so ./gobind failed: exit status 2

make: *** [bindings-android] Error 1
```

**Sample code / test case**

Reproduce by:
1. Cloning repo.
2. Changing into cmd/aries-agent-mobile
3. Executing make bindings-android

Does anybody know if I am still missing something? Does it work on your end? Would it be possible for this repo to serve pre-built aar bindings for all new releases?

**Comment by mjolk** [comment]
i got it working on the v0.1.6 branch, had the same failure on main branch

**Comment by nodh** [comment]
I've got the same error on tagged commit `v0.1.6` ...

**Comment by Marco77577** [comment]
@mjolk Thank you, works for me as well on v0.1.6. So maybe we are only supposed to build the main release versions. I hope it will be fixed though in time for the next release.

**Comment by mjolk** [comment]
just fyi i succeeded in building from main by limiting generated bindings to: ANDROID_TARGET = android/arm64,android/amd64

**Comment by Marco77577** [comment]
Indeed, this worked.

For people wondering how to set the Android target: look for the `ANDROID_TARGET` variable in the `Makefile` and replace it by the values posted above by @mjolk.
