### ISSUE TITLE
Can't connect to an aries-cloudagent-python agent

### ISSUE THREAD

**Issue by afrancoc2000** [hyperledger/aries-framework-go#3000]
**What I'm trying to do**

I'm trying to connect to an ACA-Py agent but haven't been able to do it, I have seen the interop tests, can someone please point me in the direction of the bdd tests to replicate them?

This is what I'm doing:

I tried running the makefile like this but then I could see that the GO_TAGS are not being taken into account inside agent-rest recipe.

    GO_TAGS=ACAPyInterop make agent-rest-docker

So, I created a Dockerfile in ./images/agent-rest-acapy-interop like this:

	ARG GO_VER
	ARG ALPINE_VER

	FROM golang:${GO_VER}-alpine${ALPINE_VER} as golang
	RUN apk add --no-cache \
		gcc \
		musl-dev \
		git \
		libtool \
		bash \
		make;
	ADD . $GOPATH/src/github.com/hyperledger/aries-framework-go
	WORKDIR $GOPATH/src/github.com/hyperledger/aries-framework-go
	ENV EXECUTABLES go git

	FROM golang as aries-framework
	LABEL org.opencontainers.image.source https://github.com/hyperledger/aries-framework-go

	ARG GO_TAGS
	ARG GOPROXY
	RUN GO_TAGS=${GO_TAGS} GOPROXY=${GOPROXY} make agent-rest-acapy-interop

	FROM alpine:${ALPINE_VER} as base
	RUN apk add -U --no-cache ca-certificates
	COPY --from=aries-framework /go/src/github.com/hyperledger/aries-framework-go/build/bin/aries-agent-rest /usr/local/bin
	ENTRYPOINT ["aries-agent-rest"]

And then added a recipe to the Makefile like this: 

	.PHONY: agent-rest-docker-acapy-interop
	agent-rest-docker-acapy-interop:
		@echo "Building aries agent rest docker image"
		@docker build -f ./images/agent-rest-acapy-interop/Dockerfile --no-cache -t $(DOCKER_OUTPUT_NS)/$(AGENT_REST_IMAGE_NAME):latest \
		--build-arg GO_VER=$(GO_VER) \
		--build-arg ALPINE_VER=$(ALPINE_VER) \
		--build-arg GO_TAGS=$(GO_TAGS) \
		--build-arg GOPROXY=$(GOPROXY) .

And ran it like this: 

    make agent-rest-docker-acapy-interop

I created a Go Agent using this docker-compose: 

    version: '2'
    services:

      agent1.mediator.com:
        container_name: agent1.mediator.com
        image: aries-framework-go/agent-rest:0.1.7-interop
        environment:
          - ARIESD_API_HOST=0.0.0.0:8092
          - ARIESD_INBOUND_HOST=http@0.0.0.0:8091
          - ARIESD_INBOUND_HOST_EXTERNAL=http@http://agent1.mediator.com:8091
          - ARIESD_WEBHOOK_URL=http://controller.mediator.com:8095/event
          - ARIESD_DEFAULT_LABEL=mediator-agent-1
          - ARIESD_DATABASE_TYPE=leveldb
          - ARIESD_DATABASE_PREFIX=mediator
          - ARIESD_DATABASE_TIMEOUT=60
          - ARIESD_OUTBOUND_TRANSPORT=http
          - ARIESD_LOG_LEVEL=DEBUG
          - ARIESD_HTTP_RESOLVER=did:peer@http://dev.greenlight.bcovrin.vonx.io
        ports:
          - 8091:8091
          - 8092:8092
        volumes:
          - ./certificates:/etc/tls
        entrypoint: ""
        command: /bin/sh -c "cp /etc/tls/* /usr/local/share/ca-certificates/;update-ca-certificates; aries-agent-rest start"
        networks:
          - bdd_net

    networks:
      bdd_net:
        name: bdd_net
        driver: bridge

Modified Python agent adding this to the run_demo file:

    DOCKER_ENV="${DOCKER_ENV} -e ACAPY_EMIT_NEW_DIDCOMM_PREFIX=true"
    $DOCKER run --name $AGENT --rm -it ${DOCKER_OPTS} \
      --network=bdd_net \
      -p 0.0.0.0:$AGENT_PORT_RANGE:$AGENT_PORT_RANGE \
      ${DOCKER_VOL} \
      $DOCKER_ENV \
      faber-alice-demo $AGENT_MODULE --port $AGENT_PORT $ARGS

And ran it like this:

    LEDGER_URL=http://dev.greenlight.bcovrin.vonx.io ./run_demo faber --events --no-auto --bg

I tested both didexchange and out-of-band from each endpoint with no luck.

This is what happens in didexchange with a python invitation:

    http://localhost:8021/connections/create-invitation

    {
    "connection_id": "653a6dbc-4773-4593-9c44-aa60dc1e39e8",
    "invitation": {
        "@type": "https://didcomm.org/connections/1.0/invitation",
        "@id": "79d0cd05-0bd4-4cd8-ad6e-759f5403ffce",
        "label": "faber.agent",
        "serviceEndpoint": "http://192.168.65.3:8020",
        "recipientKeys": [
        "7Y9yzF5vf9phY5ugBe1SifLB8zeGcnMz2BRqV4q6Hmxf"
        ]
    },
    "invitation_url": "http://192.168.65.3:8020?c_i=eyJAdHlwZSI6ICJodHRwczovL2RpZGNvbW0ub3JnL2Nvbm5lY3Rpb25zLzEuMC9pbnZpdGF0aW9uIiwgIkBpZCI6ICI3OWQwY2QwNS0wYmQ0LTRjZDgtYWQ2ZS03NTlmNTQwM2ZmY2UiLCAibGFiZWwiOiAiZmFiZXIuYWdlbnQiLCAic2VydmljZUVuZHBvaW50IjogImh0dHA6Ly8xOTIuMTY4LjY1LjM6ODAyMCIsICJyZWNpcGllbnRLZXlzIjogWyI3WTl5ekY1dmY5cGhZNXVnQmUxU2lmTEI4emVHY25NejJCUnFWNHE2SG14ZiJdfQ=="
    }

    curl --request POST \
    --url http://localhost:8092/connections/receive-invitation \
    --header 'Content-Type: application/json' \
    --header 'accept: application/json' \
    --data '{
        "@type": "https://didcomm.org/connections/1.0/invitation",
        "@id": "79d0cd05-0bd4-4cd8-ad6e-759f5403ffce",
        "label": "faber.agent",
        "serviceEndpoint": "http://192.168.65.3:8020",
        "recipientKeys": [
        "7Y9yzF5vf9phY5ugBe1SifLB8zeGcnMz2BRqV4q6Hmxf"
        ]
    }'

    {
        "code": 2003,
        "message": "handleInvitation: failed from didexchange service handle: handle inbound - next state : unrecognized msgType: https://didcomm.org/connections/1.0/invitation"
    }

This is what happens in didexchange with a go invitation:

    curl --request POST \
    --url http://localhost:8092/connections/create-invitation \
    --header 'Content-Type: application/json' \
    --header 'accept: application/json' \
    --data '{}'

    {
        "invitation": {
        "serviceEndpoint": "http://agent1.mediator.com:8091",
        "recipientKeys": [
            "did:key:z6Mki8Wxz2miMkixMmtebCCceFH2p8pDXMai65paBR2Yhnme"
        ],
        "@id": "446d99d2-e54e-4151-bfd4-fba302d4b3c9",
        "label": "mediator-agent-1",
        "@type": "https://didcomm.org/didexchange/1.0/invitation"
        },
        "alias": "",
        "invitation_url": ""
    }

    curl --request POST \
    --url http://localhost:8021/connections/receive-invitation \
    --header 'Content-Type: application/json' \
    --data '{
        "serviceEndpoint": "http://agent1.mediator.com:8091",
        "recipientKeys": [
        "did:key:z6Mki8Wxz2miMkixMmtebCCceFH2p8pDXMai65paBR2Yhnme"
        ],
        "@id": "446d99d2-e54e-4151-bfd4-fba302d4b3c9",
        "label": "mediator-agent-1",
        "@type": "https://didcomm.org/didexchange/1.0/invitation"
    }'

    {
        "recipientKeys": {
        "0": [
            "Value did:key:z6Mki8Wxz2miMkixMmtebCCceFH2p8pDXMai65paBR2Yhnme is not a raw Ed25519VerificationKey2018 key"
        ]
        }
    }

Doing out of band from python:

    http://localhost:8021/connections/create-invitation

    {
    "trace": false,
    "invitation": {
        "@type": "https://didcomm.org/out-of-band/1.0/invitation",
        "@id": "4c948dd7-b471-4e45-8a9f-bb0369cdb2f1",
        "services": [
        {
            "id": "#inline",
            "type": "did-communication",
            "recipientKeys": [
            "did:key:z6Mkv5mG3aAF8ibwiAQKrRPPPBrXJW6y2uh1nmb2oPGMaJth"
            ],
            "serviceEndpoint": "http://192.168.65.3:8020"
        }
        ],
        "handshake_protocols": [
        "https://didcomm.org/didexchange/1.0"
        ],
        "label": "faber.agent"
    },
    "invitation_url": "http://192.168.65.3:8020?oob=eyJAdHlwZSI6ICJodHRwczovL2RpZGNvbW0ub3JnL291dC1vZi1iYW5kLzEuMC9pbnZpdGF0aW9uIiwgIkBpZCI6ICI0Yzk0OGRkNy1iNDcxLTRlNDUtOGE5Zi1iYjAzNjljZGIyZjEiLCAic2VydmljZXMiOiBbeyJpZCI6ICIjaW5saW5lIiwgInR5cGUiOiAiZGlkLWNvbW11bmljYXRpb24iLCAicmVjaXBpZW50S2V5cyI6IFsiZGlkOmtleTp6Nk1rdjVtRzNhQUY4aWJ3aUFRS3JSUFBQQnJYSlc2eTJ1aDFubWIyb1BHTWFKdGgiXSwgInNlcnZpY2VFbmRwb2ludCI6ICJodHRwOi8vMTkyLjE2OC42NS4zOjgwMjAifV0sICJoYW5kc2hha2VfcHJvdG9jb2xzIjogWyJodHRwczovL2RpZGNvbW0ub3JnL2RpZGV4Y2hhbmdlLzEuMCJdLCAibGFiZWwiOiAiZmFiZXIuYWdlbnQifQ==",
    "state": "initial",
    "invi_msg_id": "4c948dd7-b471-4e45-8a9f-bb0369cdb2f1"
    }

    curl --request POST \
    --url http://localhost:8092/outofband/accept-invitation \
    --header 'Content-Type: application/json' \
    --header 'accept: application/json' \
    --data '{
        "invitation":{
        "@type": "https://didcomm.org/out-of-band/1.0/invitation",
        "@id": "4c948dd7-b471-4e45-8a9f-bb0369cdb2f1",
        "services": [
        {
            "id": "#inline",
            "type": "did-communication",
            "recipientKeys": [
            "did:key:z6Mkv5mG3aAF8ibwiAQKrRPPPBrXJW6y2uh1nmb2oPGMaJth"
            ],
            "serviceEndpoint": "http://192.168.65.3:8020"
        }
        ],
        "handshake_protocols": [
        "https://didcomm.org/didexchange/1.0"
        ],
        "label": "faber.agent"
    },
        "my_label": "mediator-agent-1"
    }'

    A connection is created but when I accept the request I get an 415 error in the logs

    http://localhost:8021/connections/63d16d0a-f866-42ed-b1a9-f447598d979b/accept-request

    aries_cloudagent.transport.outbound.base.OutboundTransportError: Unexpected response status 415, caused by: Unsupported Media Type

Doing out of band from go:

    curl --request POST \
    --url http://localhost:8092/outofband/create-invitation \
    --header 'Content-Type: application/json' \
    --header 'accept: application/json' \
    --data '{
        "label": "Mediador"
    }'

    {
        "invitation": {
        "@id": "80114133-5551-4bfe-a9bd-cf7792d9617a",
        "@type": "https://didcomm.org/out-of-band/1.0/invitation",
        "label": "Mediador",
        "services": [
            {
            "id": "9af5b535-5c48-4515-8fe8-1b284aa712fb",
            "type": "did-communication",
            "recipientKeys": [
                "did:key:z6MkuDLr2KYqYHcZnWPXP1hUuKpwMYSa43mckVJ1mAgsaDwP"
            ],
            "serviceEndpoint": "http://agent1.mediator.com:8091"
            }
        ],
        "accept": [
            "didcomm/aip2;env=rfc19"
        ],
        "handshake_protocols": [
            "https://didcomm.org/didexchange/1.0"
        ]
        }
    }

    curl --request POST \
    --url http://localhost:8021/out-of-band/receive-invitation \
    --header 'Content-Type: application/json' \
    --data '{
        "@id": "80114133-5551-4bfe-a9bd-cf7792d9617a",
        "@type": "https://didcomm.org/out-of-band/1.0/invitation",
        "label": "Mediador",
        "services": [
        {
            "id": "9af5b535-5c48-4515-8fe8-1b284aa712fb",
            "type": "did-communication",
            "recipientKeys": [
            "did:key:z6MkuDLr2KYqYHcZnWPXP1hUuKpwMYSa43mckVJ1mAgsaDwP"
            ],
            "serviceEndpoint": "http://agent1.mediator.com:8091"
        }
        ],
        "accept": [
        "didcomm/aip2;env=rfc19"
        ],
        "handshake_protocols": [
        "https://didcomm.org/didexchange/1.0"
        ]
    }'

    {
        "their_label": "Mediador",
        "invitation_mode": "once",
        "their_role": "inviter",
        "connection_protocol": "didexchange/1.0",
        "invitation_msg_id": "80114133-5551-4bfe-a9bd-cf7792d9617a",
        "state": "invitation",
        "updated_at": "2021-09-28 01:09:32.683916Z",
        "connection_id": "c3f8ef41-19ef-4a62-bd60-9cd25b59e851",
        "invitation_key": "Fm5oS5JQCk86g1YphSje4EGwXyAieAXG4UP5vtirf1A1",
        "rfc23_state": "invitation-received",
        "routing_state": "none",
        "accept": "manual",
        "created_at": "2021-09-28 01:09:32.683916Z"
    }

but connection doesn't change to completed and there aren't new errors
I can see all test pass in the [interop site](https://aries-interop.info/afgo.html) although there's a weird comment saying they aren't running.

I guess I must have some variables wrong, creating the agents or creating the invitations, maybe did:peer is not the right method or I should set some different type of encription using these variables: ARIESD_KEY_TYPE, ARIESD_KEY_AGREEMENT_TYPE, ARIESD_MEDIA_TYPE_PROFILES, I'm not sure how to create a raw Ed25519VerificationKey2018 key I thought that running the interop image would take care of that, or make them recognize the same msgType, or maybe using json-ld credentials somewhere?.

Can someone please point me in the right direction?

Thanks

**Comment by afrancoc2000** [comment]
Found tests [here](https://github.com/hyperledger/aries-agent-test-harness)

**Comment by Moopli** [comment]
I have to admit I'm not really sure why your testing is failing - but I'm also not familiar enough with ACA-Py to know if you're invoking it correctly to make it cooperate with AFGO. The best place to look for examples is the aries agent test harness, where you can run a didexchange example and check the logs for what the agent controller (called the backchannel in AATH) sends to the agent, and what the agent messages are.

> there's a weird comment saying they aren't running

This one's easy :)
The weird comment was accurate a few months ago, and hadn't been removed when tests were recently fixed - I made a PR to fix that just yesterday, so the automated tests that will run today should finally remove those comments.

> Found tests [here](https://github.com/hyperledger/aries-agent-test-harness)
Yeah, this is the place.

**Comment by afrancoc2000** [comment]
@Moopli Thanks!!! I'm reading right now the tests and learning a lot, found the universal-resolver to be able to read DIDs from an Indy VDR, and looking at how the agents are being setup, still haven't managed to connect my two agents but I will post it when I found out.

Thank you very much

**Comment by afrancoc2000** [comment]
Hi everyone, 

I checked the tests and I see that the implemented protocol uses out-of-band, so, I'm leaving behind the connection using the RFC-0160. This is what I have to the moment:

Out of band from python:

The problem here was that I was calling the wrong method in the python agent, instead of `http://localhost:8021/connections/<connection-id>/accept-request` the method that should be used is `http://localhost:8021/didexchange/<connection-id>/accept-request`. This way the connection is completed and the agents are connected.

Out of band from go:

One of the problems here was, that after receiving the invitation, in the python agent, the invitation must be accepted. An extra step that isn't needed in the go agent, so I added an extra step like this: `http://localhost:8041/didexchange/<connection_id>/accept-invitation`, after accepting the invite, the connection is created in the go agent, step that I was missing before. Now I'm facing a new problem, after accepting the request in the go agent I get a new error:

```
{
  "code": 2005,
  "message": "did exchange client - accept exchange request: failed to execute state 'responded': handle inbound request: handle inbound request: recipientKeyAsDIDKey: invalid DID Doc service type: 'IndyAgent'"
}
```

I'm still figuring this one out.

Thanks

**Comment by Moopli** [comment]
That's odd, if the go agent is built with the `ACAPyInterop` build tag, it shouldn't be running into that issue, it's one of the interop oddities due to acapy being partly between aries interop profiles 1.0 (which is generally much more indy-focused) and 2.0.

**Comment by afrancoc2000** [comment]
hmmm I'm going to build it again, thanks!

**Comment by afrancoc2000** [comment]
It works!!! Thank you very much!!! I guess maybe between all the tests my docker images got mixed up. Thanks again!
