### ISSUE TITLE
Connectionless credential and presentation exchnage

### ISSUE THREAD

**Issue by TimoGlastra** [hyperledger/aries-framework-go#3173]
**What I'm trying to do**

The Out of Band protocol allows to create an invitation without any handshake protocols, allowing for a connectionless exchange. When interacting with the rest API and creating an OOB invitation without handshake protocols it simply adds the handshake protocols and removes the attachments items.

**Expected result**

I would suspect the API to allow not passing handshake_protocols to perform a connectionless exchange

**Actual result**

handshake protocols is always added. Looking at the code I also can't find any references to the `~service` decorator. This makes me believe connectionless exchanges are not supported in Aries Framework Go. Is this correct?

**Sample code / test case**

Call `outofband/create-invitation` with the following payload:

```json
{
    "label": "aute sunt dolore",
    "protocols": [
        "https://didcomm.org/didexchange/2.0"
    ],
 "attachments": [
     {
        "id": "request-0",
        "media_type": "application/json",
        "data": {
          "json": {
            "@type": "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/present-proof/2.0/request-presentation",
            "@id": "9203ebcc-e54c-4a61-9a4a-6ede677a3b6d",
            "request_presentations~attach": [
              {
                "@id": "indy",
                "mime-type": "application/json",
                "data": {
                  "base64": "eyJuYW1lIjogIlByb29mIHJlcXVlc3QiLCAicmVxdWVzdGVkX2F0dHJpYnV0ZXMiOiB7ImFkZGl0aW9uYWxQcm9wMSI6IHsibmFtZSI6ICJmYXZvdXJpdGVEcmluayIsICJyZXN0cmljdGlvbnMiOiBbXX19LCAicmVxdWVzdGVkX3ByZWRpY2F0ZXMiOiB7fSwgInZlcnNpb24iOiAiMS4wIiwgIm5vbmNlIjogIjEwNzI2NDI0ODkxMTI2OTA4OTAyMTk0NyJ9"
                }
              }
            ],
            "will_confirm": true,
            "formats": [
              {
                "attach_id": "indy",
                "format": "hlindy/proof-req@v2.0"
              }
            ]
          }
        }
      }
 ]
}
```

**Comment by Moopli** [comment]
@TimoGlastra yeah, that's correct - afgo doesn't support connectionless didcomm v1. If you want a connectionless presentation exchange, I'd recommend using DIDComm V2, since we've put in a lot of effort recently to implement that ;).

**Comment by TimoGlastra** [comment]
Thanks @Moopli. I'm actually working on adding this to AATH to cover AIP 2 scenarios, so can't use DIDComm v2. But if it's not supported, no reason in needing it in AATH :)
