### ISSUE TITLE
Proofs with JWS values are not signed correctly

### ISSUE THREAD

**Issue by decentralgabe** [hyperledger/aries-framework-go#3181]
As part of the [Data Integrity spec's CreateVerifyHash algorithm](https://w3c-ccg.github.io/data-integrity-spec/#create-verify-hash-algorithm) step (2) describes:

> If the [proofValue](https://w3c-ccg.github.io/data-integrity-spec/#dfn-proofvalue) parameter, such as jws, exists in options, remove the entry.

However, the implementation here includes a header + ".." as input to the CVH method:
- https://github.com/hyperledger/aries-framework-go/blob/main/pkg/doc/signature/signer/signer.go#L123

And does not remove the `jws` value in the CVH method:
- https://github.com/hyperledger/aries-framework-go/blob/main/pkg/doc/signature/proof/data.go#L59

I believe the effect of this is the code not creating valid signed documents, or being able to verify valid signed documents that use suites that leverage the `jws` property, including the [JsonWebSignature2020 suite](https://w3c-ccg.github.io/lds-jws2020/).

**Comment by OR13** [comment]
cc @troyronda

**Comment by Baha-sk** [comment]
>As part of the [Data Integrity spec's CreateVerifyHash algorithm](https://w3c-ccg.github.io/data-integrity-spec/#create-verify-hash-algorithm) step (2) describes:

>>If the [proofValue](https://w3c-ccg.github.io/data-integrity-spec/#dfn-proofvalue) parameter, such as jws, exists in options, remove the entry.

>However, the implementation here includes a header + ".." as input to the CVH method:

If I understand correctly, `If the [proofValue](https://w3c-ccg.github.io/data-integrity-spec/#dfn-proofvalue) parameter, such as jws, exists in options, remove the entry.` means remove the entry from proofValue that is used to build the canonical Doc for JWS signing, which is done here:
https://github.com/hyperledger/aries-framework-go/blob/main/pkg/doc/signature/proof/jws.go#L120-L123

in `prepareJWSProof()` function. This function is called earlier in the same file at line [86](https://github.com/hyperledger/aries-framework-go/blob/main/pkg/doc/signature/proof/jws.go#L86). 

The digest created at line [96](https://github.com/hyperledger/aries-framework-go/blob/main/pkg/doc/signature/proof/jws.go#L98) does not include the JWS as the header.

Also if you follow `prepareDocumentForJWS()` call at line [93](https://github.com/hyperledger/aries-framework-go/blob/main/pkg/doc/signature/proof/jws.go#L93), the canonical document is stripped from any proofs.


Finally, the end of that `createVerifyJWS()` handles the addition of the JWE in the headers. I believe this is the JWT header (which happens to be the original JWS) added in the headers for JWS compliance to integrity check the original JWT. As you see in the code above, it *not* added in the document being signed.

Does this answer the issue?

**Comment by decentralgabe** [comment]
Thanks for the clarification @Baha-sk. It does appear the library has the correct functionality. I was thrown off by [this line](https://github.com/hyperledger/aries-framework-go/blob/main/pkg/doc/signature/signer/signer.go#L123) and I'm still not clear on it's utility 🤔

**Comment by Baha-sk** [comment]
no problem @decentralgabe , this line is only used to set the JWT header, but it's not used in the signing/verification operation. The sole purpose is to set the header as i mentioned earlier. Ref code [here](https://github.com/hyperledger/aries-framework-go/blob/main/pkg/doc/signature/proof/jws.go#L102-L107). But this is only the returned JWS header, clients can ignore/skip this header and use only the body for verifications. It's there to integrity check the original JWS.

**Comment by Baha-sk** [comment]
if you're satisfied with the answer, please close the issue.
