### ISSUE TITLE
Update DIDComm V2 Endpoint to include a URI, routingKeys and Accept fields

### ISSUE THREAD

**Issue by baha-ai** [hyperledger/aries-framework-go#3219]
spec udpate ref: https://github.com/decentralized-identity/didcomm-messaging/pull/352

**Comment by lauravuo-techlab** [comment]
It seems the PR for this feature #3223 has broken the ACAPy interoperability. The code does not build with the feature flag `ACAPyInterop`

**Comment by Baha-sk** [comment]
Thanks for the update @lauravuo-techlab 

The PR pushed and merged earlier in the last couple of weeks to fix this issue did a blunt replacement to DIDComm V2 ServiceEndpoint update. 

This is not the right approach, I'm currently updating AFGO to support a more flexible DIDComm V1 / V2 ServiceEndpoint support. Currently running some tests to make sure the changes don't break anything then I'll be pushing a new PR.

**Comment by lauravuo-techlab** [comment]
Thanks for the info 👍

**Comment by Baha-sk** [comment]
It's finally merged now, had some issues with didcomm v1 vs v2 interop, all seems to work now. 

@lauravuo-techlab, Can you try again with the latest AFGO commit? 

I am closing this issue for now. If you still have compilation issues, please open a new one.

Thanks.

**Comment by lauravuo-techlab** [comment]
I can confirm that the code now builds with the interop-flag. The interoperability functionality is broken though as you can see from [the Aries harness reports](https://allure.vonx.io/api/allure-docker-service/projects/afgo-b-acapy/reports/latest/index.html).
