### ISSUE TITLE
DID method to be used during DID Exchange

### ISSUE THREAD

**Issue by sudeshrshetty** [hyperledger/aries-framework-go#322]
DID Exchange service need to provide DID method name for creating DID.

belongs to #42

**Comment by llorllale** [comment]
@sudeshrshetty as we spoke, from a high level point of view:

* the `didexchange.Service` should not concern itself with what method the DIDDoc should be created with.
* The [`didexchange.provider`](https://github.com/hyperledger/aries-framework-go/blob/bd040c0e2defdd5dbcdaec02148786250af3910f/pkg/didcomm/protocol/didexchange/service.go#L64)  interface should define a type other than `wallet.DIDCreator` with a function that *does not* need the method as an input argument
