### ISSUE TITLE
[VCWallet] Open/Close - replace UUID token with JWT tokens

### ISSUE THREAD

**Issue by sudeshrshetty** [hyperledger/aries-framework-go#3246]
Currently wallet is returning simple UUID strings as tokens when unlocked for subsequent wallet use.

It has to be replaced with JWTs with proper expiry & refresh mechanisms.

**Comment by sudeshrshetty** [comment]
@vkubiv

**Comment by vkubiv** [comment]
**Research results for sharing KMS for VC Wallet between different tabs.**

We are using a passphrase to generate AES Key used to lock KMS. Some mechanisms to share that data will allow recreating of the session object with a proper KMS instance.

**Comment by sudeshrshetty** [comment]
To be closed since it is done as per https://github.com/hyperledger/aries-framework-go/pull/3249.

For separating cache with token, use #2556
