### ISSUE TITLE
Accept invitation and save it.

### ISSUE THREAD

**Issue by jmerino12** [hyperledger/aries-framework-go#3267]
(compile version 0.1.8, for Android)

**What I'm trying to do**

I am trying to accept an outbound invitation, with my storage configured, to persist the data.

**Expected result**

Accept the invitation and save that connection.

**Actual result**

Error, it does not accept the invitation, nor does it change its status, much less save it

**Sample code / test case**

`I/GoLog:  [aries-framework/did-exchange/service] 2022/07/05 13:57:03 UTC - n/a -> ERROR command=[didexchange] action=[processMessage] [msgType=[oob-invitation] msgID=[c3a9050a-3b13-47de-b10d-05a47f8488ab] connectionID=[9dd4bd62-6184-4984-ae85-f40e2a7cfab8]] errMsg=[failed to execute state 'requested': failed to handle inbound oob invitation : failed to create and export public key: createSigningVM: createAndExportPubKeyBytes: failed to create new key: create: failed to store keyset: writeToStore: failed to write buffer to store: requested ID 'pa_wUKhb4SlPh2SyAlVOQM5MvTJz_8-Q1YNPTEIGEwU' already exists, cannot write keyset]
`

**Comment by afrancoc2000** [comment]
Found the problem [here](https://github.com/hyperledger/aries-framework-go/blob/566dff81e2ab98c0e33ffa4cbcee1bb926857c4f/pkg/kms/localkms/localkms_writer.go#L75) the mobile agent doesn't recognize the DataNotFound Exception, we are trying with a RuntimeException("data not found"), any ideas how should we pass this type of error?

Thanks

**Comment by afrancoc2000** [comment]
So, to be able to get it to work we created an exception thrower like this in pkg\wrappers\command\exceptionthrower.go:

```
package command

import "github.com/hyperledger/aries-framework-go/spi/storage"

type ExceptionThrower struct {
}


// CreateInvitation creates a new connection invitation.
func (thrower *ExceptionThrower) ThrowDataNotFoundException() error {
	return storage.ErrDataNotFound
}
```

We are using this exception where data not found is expected, is there a better way? thanks!

**Comment by jmerino12** [comment]
I'm going to close the topic, write us anything
