### ISSUE TITLE
Add jwt-vc test suites supporting AFGO

### ISSUE THREAD

**Issue by Baha-sk** [hyperledger/aries-framework-go#3288]
Add a new implementation in https://github.com/decentralized-identity/JWS-Test-Suite

also update interop data as necessary

**Comment by sudeshrshetty** [comment]
Need support for both JsonWebSignature2020 and JWT.

**Comment by mishasizov-SK** [comment]
PR: https://github.com/hyperledger/aries-framework-go/pull/3315
