### ISSUE TITLE
Support ability in AFGO to create and parse vc and vp in JWT format

### ISSUE THREAD

**Issue by fqutishat** [hyperledger/aries-framework-go#3314]
https://www.w3.org/TR/vc-data-model/

**Comment by Moopli** [comment]
Acceptance criteria: 
- successful sdk BDD test where:
  - An agent creates a JWT VC using afgo APIs
  - Same agent creates a JWT VP using afgo APIs, using the above JWT VC
  - Same agent verifies the above JWT VP
- Successful controller BDD test, same steps as above

**Comment by fqutishat** [comment]
Covers all use cases, signing (by DIDs), verifying, deriving, signature suites

**Comment by sudeshrshetty** [comment]
1.  Sign JWT Credential  - Add it to wallet - get from wallet - verify JWT Credential
2. Get JWT credential (without proof) - Call wallet.issue() - get signed JWT credential back - verify JWT credential
3. Use JWT Signed credentials from previous steps - call wallet.prove() - get a JWT presentation back - verify JWT presentation 
4. Add all the credentials from previous steps to wallet - call wallet.Add(JWT Credential) - wallet.Query() - get query result as JWT presentation - user consents (call wallet.prove(...) on user consent)
5. Try to cover wallet.getAll() credential (JSON LD & JWT mixed)
6. Try to support all Query Types supported by wallet
7. Test Credential manifest resolve feature

**Comment by fqutishat** [comment]
@mishasizov-SK is working on this task

**Comment by mishasizov-SK** [comment]
PR: https://github.com/hyperledger/aries-framework-go/pull/3334

**Comment by fqutishat** [comment]
https://github.com/hyperledger/aries-framework-go/pull/3334

**Comment by Moopli** [comment]
Finished in https://github.com/hyperledger/aries-framework-go/pull/3368
