### ISSUE TITLE
Support for JWT in universal wallet implementation 

### ISSUE THREAD

**Issue by fqutishat** [hyperledger/aries-framework-go#3326]

**Comment by fqutishat** [comment]
BDD tests for universal wallet JWT support

Sign JWT Credential - Add it to wallet - get from wallet - verify JWT Credential
Get JWT credential (without proof) - Call wallet.issue() - get signed JWT credential back - verify JWT credential
Use JWT Signed credentials from previous steps - call wallet.prove() - get a JWT presentation back - verify JWT presentation
Add all the credentials from previous steps to wallet - call wallet.Add(JWT Credential) - wallet.Query() - get query result as JWT presentation - user consents (call wallet.prove(...) on user consent)
Try to cover wallet.getAll() credential (JSON LD & JWT mixed)
Try to support all Query Types supported by wallet
Test Credential manifest resolve feature

**Comment by Moopli** [comment]
- Include Query tests that cover presentation exchange v2

**Comment by fqutishat** [comment]
https://github.com/hyperledger/aries-framework-go/pull/3368
