### ISSUE TITLE
JSON LD Contexts in JWT VCs

### ISSUE THREAD

**Issue by sudeshrshetty** [hyperledger/aries-framework-go#3351]
Currently JSON LD contexts in JWT VCs are required, but that doesn't clearly enforces contexts beyond Verifiable Credential data model. In simple words `https://www.w3.org/2018/credentials/v1` is required but any additional contexts for custom properties can be optional.

Example: https://github.com/decentralized-identity/jwt-vc-presentation-profile/pull/52/files#diff-76909e03d654c1deb30b8258103972c9fa20ccb9411e72f0dc2436151c70ddc9R2-R4

**Objective of this task:**
For JWT VCs,
- [ ] make VC data model context as required and additional contexts can be optional
- [ ] If [strict validation option](https://github.com/hyperledger/aries-framework-go/blob/6c0c224401eed96cc4ad6d8478664374885596fc/pkg/doc/verifiable/credential.go#L578) enabled while parsing JWT VCs, then JSON LD  data model validation of JWT VC should be performed.

**Comment by sudeshrshetty** [comment]
@mishasizov-SK

**Comment by mishasizov-SK** [comment]
PR: https://github.com/hyperledger/aries-framework-go/pull/3357
