### ISSUE TITLE
Refactoring creation of serialized JWT from Verifiable Credential 

### ISSUE THREAD

**Issue by kdimak** [hyperledger/aries-framework-go#339]
In verifiable.Credential.JWT() method, the private key is passed as parameter. According to @llorllale, 
>Private keys will never leave the wallet, therefore they cannot be passed in as a parameter to anything outside of the wallet itself. 
Therefore, refactoring is needed here.

**Comment by llorllale** [comment]
See https://github.com/hyperledger/aries-framework-go/pull/312#discussion_r327796375

**Comment by kdimak** [comment]
It also applies to Verifiable Credential marshalling to JWS.

**Comment by troyronda** [comment]
Somewhat related: https://github.com/hyperledger/aries-framework-go/pull/456#discussion_r334988449
