### ISSUE TITLE
Preapare the connection signature raw data as per the spec

### ISSUE THREAD

**Issue by talwinder50** [hyperledger/aries-framework-go#345]
This PR prepares the sig data as per : https://github.com/hyperledger/aries-rfcs/tree/master/features/0023-did-exchange
```

 "connection": {
    "did": "A.did@B:A",
  	"did_doc": {
      "@context": "https://w3id.org/did/v1"
      // DID Doc contents here.
    }
```
The connection attribute will be base64URL encoded and included as part of the sig_data attribute of the signed field. The result looks like this:

```
{
  "@type": "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/didexchange/1.0/response",
  "@id": "12345678900987654321",
  "~thread": {
    "thid": "The Thread ID is the Message ID (@id) of the first message in the thread"
  },
  "connection~sig": {
    "@type":"did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/signature/1.0/ed25519Sha512_single",
    "signature": "digital signature function output",
    **"sig_data": "base64URL(64bit_integer_from_unix_epoch||connection_attribute)",**
    "signers": "signing_verkey"
  }
}
```
**The connection attribute has been removed and it's contents combined with the timestamp and encoded into the sig_data field of the new connection~sig attribute.**

sign_data needs to be validated with the raw data present in the sig_data and then should be further unmarshalled.

**Comment by llorllale** [comment]
@talwinder50 the `signature-decorator` RFC is now in Aries: https://github.com/hyperledger/aries-rfcs/blob/master/features/0234-signature-decorator/README.md
