### ISSUE TITLE
Losing disclosures while marshalling SD-JWT presentations

### ISSUE THREAD

**Issue by sudeshrshetty** [hyperledger/aries-framework-go#3505]
Due to default behaviour we added to exclude disclosures while marshalling SD-JWT VCs, marshalling presentation causes SD-JWT VCs inside presentations to lose their holder disclosures.

Fix: We will have to change default marshalling behaviour of SD-JWT credentials to include disclosures.

**Comment by Moopli** [comment]
Fixed in https://github.com/hyperledger/aries-framework-go/pull/3506
