### ISSUE TITLE
RFC 0019: Pack/Unpack

### ISSUE THREAD

**Issue by troyronda** [hyperledger/aries-framework-go#36]

**Comment by Baha-sk** [comment]
As per the DID-Comm encryption envelope spec:
https://github.com/hyperledger/aries-rfcs/blob/master/features/0019-encryption-envelope/README.md

This epic will include packing and unpacking of envelopes exchanged between DID agents.

JWE encryption/decryption is mainly used in this process for additional security/confidentiality of messages.

**Comment by Baha-sk** [comment]
outdated
