### ISSUE TITLE
Create a new Package to support Chacha20/Poly1035 encryptions/authentication (in JWE format)

### ISSUE THREAD

**Issue by Baha-sk** [hyperledger/aries-framework-go#37]
Standard JWE encryption/decryption operations does not support Chacha20 algorithm with Poly1035 authentication.

There are talks to update the JWE spec with this new addition. An IETF draft can be found here:
https://datatracker.ietf.org/doc/draft-amringer-jose-chacha/

The aim of this issue is to create a new package that will support this new JWE spec.

finally, for reference, Aries-rfc has an issue to update its spec using this new format:
https://github.com/hyperledger/aries-rfcs/issues/133

A PHP example is found here:
https://github.com/gamringer/php-authcrypt

the task here is to follow the same format in Go

Part of #36

**Comment by troyronda** [comment]
How do we plan to incorporate the modifications of go-jose into this project? Is a fork required or are we able to wrap the go-jose library and contain the modifications into this repository?

**Comment by Baha-sk** [comment]
> How do we plan to incorporate the modifications of go-jose into this project? Is a fork required or are we able to wrap the go-jose library and contain the modifications into this repository?

The changes in Go-Jose are intertwined within the framework, changes are done on a fork (and we can potentially submit a PR to merge the change but we will need the IETF draft to be come part of the JWE standard to support the merge)

**Comment by Baha-sk** [comment]
New update to this issue, forking Go-Jose is not suitable, we will instead build our own package that encrypts/decrypts JWE formatted messages using Chacha20/Poly1035 instead.
