### ISSUE TITLE
Correlate Exchange Invitation to Exchange Request

### ISSUE THREAD

**Issue by rolsonquadras** [hyperledger/aries-framework-go#387]
This query came up during the [Framework Go - Weekly planning meeting](https://wiki.hyperledger.org/display/ARIES/2019-10-01+Framework+Go+Weekly+Planning) while discussing about BDD tests. 

Scenario - Agent A sends the invitation and need to know if the flow has been completed for that invitation, i.e. State is Ack.   

Question - Can the agent map the invitation sent out to the exchange requests received? If so, how ?

Background - The [DIDExchange RFC](https://github.com/hyperledger/aries-rfcs/tree/master/features/0023-did-exchange) doesn't mention this mapping. The threadID starts after exchange request and used to map the subsequent interaction between the agents.

Caveat - Is this scenario valid ? Should the agent match exchange request to the completed status ?

**Comment by rolsonquadras** [comment]
Correlation is based on recipients public keys.

Possible use cases for this correlation between invitation and exchange request.
1. logging
2. Check for expiry
3. Check for usage count

**Comment by llorllale** [comment]
@rolsonquadras 

> Question - Can the agent map the invitation sent out to the exchange requests received? If so, how ?

Currently this can be achieved by correlating the keys on the outgoing invitation to the keys used to pack the incoming request.

> Background - The DIDExchange RFC doesn't mention this mapping. The threadID starts after exchange request and used to map the subsequent interaction between the agents.

The invitation does not belong to any thread - see hyperledger/aries-rfcs#208

> Caveat - Is this scenario valid ? Should the agent match exchange request to the completed status ?

I think it's reasonable to correlate an exchange request to an invitation. Including the hash of the invitation in the request sounds like a good approach. My only lingering doubts are w.r.t. the case when the invitation is on a DID document. (any DID document with the necessary service definition can serve as an invitation). If a hash of that DID document is sent back, I presume we would have had to first index that DID document by its hash as well as its DID.

Another possibility is include a reference to the invitation's ID in the exchange request. When the invitation is a simple DIDComm message (as shown in the RFC) then the reference would be that message's `@id`. When the invitation is derived from a DID document then the reference would be the service's `@id`.

**Comment by rolsonquadras** [comment]
Created following issues based on discussion with @troyronda @fqutishat @sandrask @sudeshrshetty.

https://github.com/hyperledger/aries-framework-go/issues/396
https://github.com/hyperledger/aries-framework-go/issues/397
https://github.com/hyperledger/aries-framework-go/issues/398
https://github.com/hyperledger/aries-framework-go/issues/400
https://github.com/hyperledger/aries-framework-go/issues/401
https://github.com/hyperledger/aries-framework-go/issues/402
https://github.com/hyperledger/aries-framework-go/issues/403

**Comment by rolsonquadras** [comment]
Creates issue for BDD test update - https://github.com/hyperledger/aries-framework-go/issues/420
