### ISSUE TITLE
Refactor Properties variable in Action/Msg event struct

### ISSUE THREAD

**Issue by rolsonquadras** [hyperledger/aries-framework-go#457]
While discussing the possible solution for #442 with @troyronda , we came across the [Properties](https://github.com/hyperledger/aries-framework-go/blob/master/pkg/didcomm/common/service/event.go#L25) variable in Action/Msg event struct.

Currently the type of that is `map[string]interface{}`. The consumer would need to know the keys for each protocol and also they would need to cast to a type for each of those keys.

Updating this to `interface{}` type would require the consumers to know the type for each protocol. The protocols can have an interface that will have functions for different properties. 

```
package service
type StateMsg struct {
	Properties interface{}
}

type DIDExchangeEvent interface {
	GetConnectionID() string
	GetInvitationID() string
}
```

```
package didexconsumer

msg = StateMsg from event

prop, ok := e.Properties.(service.DIDExchangeEvent)
// cast validation
connectionID := prop.GetConnectionID()
invitationID := prop.GetInvitationID()

```

**Comment by troyronda** [comment]
Note: in this case the Get prefix should be dropped as the methods are simple accesors.
