### ISSUE TITLE
Consistent name for Recipient Key, Verification Key, Sender Key

### ISSUE THREAD

**Issue by rolsonquadras** [hyperledger/aries-framework-go#466]
Just a small observation on [RecKeys/VerKeys](https://github.com/hyperledger/aries-framework-go/pull/463/files#diff-9988f5820bf05228e5657f2842fa071eR99) overall (not specific to this PR) : Looks like we are using different terms for these keys at different layers - Recipient Keys, Verification Keys, Sender Keys. May be we need to be consistent with names across the project.

_Originally posted by @rolsonquadras in https://github.com/hyperledger/aries-framework-go/pull/463#issuecomment-540631943_

**Comment by Moopli** [comment]
Ways we could name keys:
- who owns them? Are they owned by the agent that is handling them? Are they owned by other agents that communicate with the current agent?
- What is their purpose? Are they verification keys, signing keys, encryption keys, etc? This can be even more fine-grained, for example are they _key encryption keys_, _ephemeral keypairs_, etc.
- What is their implementation? Are they Ed25519, Curve25519, Curve448, or RSA-3072 keys, etc.

I think it's reasonable that names will vary by layer - high-level we mostly care about whether the keys are ours or theirs, which p2p (assuming peer DIDs) channel they are used for, and if they're signing keys or encryption keys - and depending on the design decision we come to for #454, pack/unpack and wallet might be the only things that touch encryption keys at all.

**Comment by Baha-sk** [comment]
We should stick to Ver or Verification keys for signing keys and Encryption Keys for encryption/decryption keys.

Recipient vs Sender keys are scoped names and should not be general. In other terms, they should be used for the context of sending/receiving messages, but they do not specify if they're used for signing or encryption. Therefore, they should not be generalized.

Currently #272 will introduce a key type (in KeyPair) for this purpose and will need to store 2 sets of key pairs in the wallet (one set for signing and another for encryption, #488). The key type should also be validated, for example Curve25519 is an encryption key while Ed25519 is a signing key type.
