### ISSUE TITLE
Peer DID: Validate Doc against DID Identifier

### ISSUE THREAD

**Issue by rolsonquadras** [hyperledger/aries-framework-go#48]
The agents exchange Peer DIDs using [DID Exchange Protocol](https://github.com/hyperledger/aries-rfcs/blob/master/features/0023-did-exchange/README.md). 

The receiving agent should have the capability to [validate](https://openssi.github.io/peer-did-method-spec/index.html#create-register) the DID Document against the name-string component of the DID Identifier. 

The generation of Identifier is described in #46.

**Comment by rolsonquadras** [comment]
Part of epic #35

**Comment by rolsonquadras** [comment]
Part of epic #35

**Comment by llorllale** [comment]
@rolsonquadras I'd like to have a model for the DID. Right now we're treating it as a mere string. It would be valuable to have a composite model for DIDs (just the DID ID) from which one could extract its components, such as its method.
