### ISSUE TITLE
Separate transient protocol storage

### ISSUE THREAD

**Issue by troyronda** [hyperledger/aries-framework-go#507]
We should allow a different storage backend for transient protocol states. In some deployments, these might simply be kept in memory (if node crashes are tolerated) or to a memcache cluster (if only cluster crashes are tolerated).

Writing all transient states to the database negatively affects performance.

**Comment by rolsonquadras** [comment]
@troyronda seems like this had been implemented as part of https://github.com/hyperledger/aries-framework-go/issues/622. If there are no pending items, can we close this ?
