### ISSUE TITLE
Allow crypto operations to use private keys

### ISSUE THREAD

**Issue by Moopli** [hyperledger/aries-framework-go#511]
The wallet/keystore holds and manages keys, and the crypters, signer, and various operations related to VCs, DIDs, etc require the use of private keys.

If the keystore is a subpackage of, say, `pkg/crypto`, then `pkg/crypto/internal` can contain functions that access private keys from the keystore, allowing any other package within `pkg/crypto` to access private keys.

This sidesteps the issue where we have to create wrapper functions in the wallet for any crypto operation, so the wallet can call the wrapped function and provide any private keys needed. Crypto operations can be implemented in packages in `pkg/crypto`, and thus have access to private keys.

This way, the rest of the agent library still can't access private keys. We can still be rigorous about minimizing what has access to private keys, by minimizing what will go inside the crypto package, keeping only the primitives/operations that need a private key for their processing, and ensuring they never expose those private keys.

**Comment by Moopli** [comment]
@Baha-sk this issue is obsolete thanks to tink and kms integration, right?

**Comment by Baha-sk** [comment]
> @Baha-sk this issue is obsolete thanks to tink and kms integration, right?

this is correct @Moopli, i'm closing this issue
