### ISSUE TITLE
Events parameters for pre state

### ISSUE THREAD

**Issue by talwinder50** [hyperledger/aries-framework-go#578]
We need to reconsider where we are creating the connectionID. Without any correlation, the consumers will not be able to fetch connection details (if required). For now, can we add a TODO ?

**Comment by rolsonquadras** [comment]
This was added as part of another PR - https://github.com/hyperledger/aries-framework-go/pull/634/files#diff-f761c91e753eba1c42a68076df06ce12R219.

**Comment by rolsonquadras** [comment]
@talwinder50 can you please close this ?
