### ISSUE TITLE
Keep extra fields of termsOfUse of VC in a map.

### ISSUE THREAD

**Issue by kdimak** [hyperledger/aries-framework-go#586]
Currently we use `interface{}` type for `termsOfUse` what is too generic. According to [VC spec](https://w3c.github.io/vc-data-model/#terms-of-use), `type` field is mandatory and `id` field is optional, and that "precise contents of each term of use is determined by the specific termsOfUse type definition".
We should use 'typedID' type and keep extra fields in `map[string]interface{}`.

**Comment by llorllale** [comment]
@kdimak 

>  We should use 'typedID' type and keep extra fields in map[string]interface{}.

Would it make sense to instead implement a "decoder" similar to `verifiable.CredentialDecoder`?
