### ISSUE TITLE
Reference Agent Controller API

### ISSUE THREAD

**Issue by alikic** [hyperledger/aries-framework-go#67]
Need a REST API (Swagger) that allows the control of the reference agent.

Should be loosely based on hl/aries-cloudagent-python

**Comment by llorllale** [comment]
This is part of epic #68

**Comment by sudeshrshetty** [comment]
**Controller API**

Open API server : REST API endpoints for each protocol with default handlers to start with (mock implementation is also an option).

**For DEMO**

build docker image for demo agent with default handlers for controller REST API server.
Simple config to add new agents for demo.
For example: to add new agent 'Bob', simply adding required configurations like port, host etc and starting new docker container for given agent.
launching tests using Swagger UI
Replacing each default handlers with reference agent (controller API) once available

**Comment by sudeshrshetty** [comment]
**Endpoints for tests:**
server
GET ​/modules Fetch the list of loaded modules
GET ​/status Fetch the server status
POST ​/status​/reset Reset statistics
GET ​/protocols Query supported protocols

action-menu
POST ​/action-menu​/{id}​/close Close the active menu associated with a connection
POST ​/action-menu​/{id}​/fetch Fetch the active menu
POST ​/action-menu​/{id}​/perform Perform an action associated with the active menu
POST ​/action-menu​/{id}​/request Request the active menu
POST ​/connections​/{id}​/send-menu Send an action menu to a connection

connection
GET ​/connections Query agent-to-agent connections
GET ​/connections​/{id} Fetch a single connection record
POST ​/connections​/create-invitation Create a new connection invitation
POST ​/connections​/receive-invitation Receive a new connection invitation
POST ​/connections​/{id}​/accept-invitation Accept a stored connection invitation
POST ​/connections​/{id}​/accept-request Accept a stored connection request
POST ​/connections​/{id}​/establish-inbound​/{ref_id} Assign another connection as the inbound connection
POST ​/connections​/{id}​/remove Remove an existing connection record

credentials
GET ​/credential​/{id} Fetch a credential from wallet by id
POST ​/credential​/{id}​/remove Remove a credential from the wallet by id
GET ​/credentials Fetch credentials from wallet

credential_exchange
GET ​/credential_exchange Fetch all credential exchange records
GET ​/credential_exchange​/{id} Fetch a single credential exchange record
POST ​/credential_exchange​/send Sends a credential and automates the entire flow
POST ​/credential_exchange​/send-offer Sends a credential offer
POST ​/credential_exchange​/{id}​/send-request Sends a credential request
POST ​/credential_exchange​/{id}​/issue Sends a credential
POST ​/credential_exchange​/{id}​/store Stores a received credential
POST ​/credential_exchange​/{id}​/problem_report Send a problem report for credential exchange
POST ​/credential_exchange​/{id}​/remove Remove an existing credential exchange record

introduction
POST ​/connections​/{id}​/start-introduction Start an introduction between two connections

presentation_exchange
GET ​/presentation_exchange Fetch all presentation exchange records
GET ​/presentation_exchange​/{id} Fetch a single presentation exchange record
GET ​/presentation_exchange​/{id}​/credentials Fetch credentials for a presentation request from wallet
GET ​/presentation_exchange​/{id}​/credentials​/{referent} Fetch credentials for a presentation request from wallet
POST ​/presentation_exchange​/create_request Creates a presentation request
POST ​/presentation_exchange​/send_request Creates and sends a presentation request
POST ​/presentation_exchange​/{id}​/send_presentation Sends a credential presentation
POST ​/presentation_exchange​/{id}​/verify_presentation Verify a received credential presentation
POST ​/presentation_exchange​/{id}​/remove Remove an existing presentation exchange record

schema
POST ​/schemas Sends a schema to the ledger
GET ​/schemas​/{id} Gets a schema from the ledger

credential-definition
POST ​/credential-definitions Sends a credential definition to the ledger
GET ​/credential-definitions​/{id} Gets a credential definition from the ledger

basicmessage
POST ​/connections​/{id}​/send-message Send a basic message to a connection
POST ​/connections​/{id}​/expire-message​/{activity_id} Expire a copyable basicmessage

trustping
POST ​/connections​/{id}​/send-ping Send a trust ping to a connection

wallet
GET ​/wallet​/did List wallet DIDs
POST ​/wallet​/did​/create Create a local DID
GET ​/wallet​/did​/public Fetch the current public DID
POST ​/wallet​/did​/public Assign the current public DID

**Comment by sudeshrshetty** [comment]
created stories 
**#93 Controller API for did exchange**
**#94 Demo : Controller API for did exchange**
**#95 Controller API : add protocols for demo with mock implementation**

**Comment by llorllale** [comment]
We'll spin this issue off into its own epic
