### ISSUE TITLE
Add thread decorator in the exchange request

### ISSUE THREAD

**Issue by talwinder50** [hyperledger/aries-framework-go#676]
"~thread": { "pthid": "<id of invitation>" },
https://github.com/hyperledger/aries-rfcs/tree/master/features/0023-did-exchange

Implement the following spec:

https://github.com/hyperledger/aries-rfcs/tree/master/features/0023-did-exchange#correlating-requests-to-invitations

**Comment by fqutishat** [comment]
#718
