### ISSUE TITLE
REST Accept Invitation doesn't check for connection ID existence

### ISSUE THREAD

**Issue by troyronda** [hyperledger/aries-framework-go#691]
Used a fake Connection ID: 'a'
http://localhost:9082/connections/a/accept-invitation

`{"state":"requested","their_did":"","created_at":"2019-11-04T23:32:32.560919Z","accept":"auto","my_did":"TAaW9Dmxa93B8e5x6iLwFJ","request_id":"678ad4b6-4e2b-40a1-804e-8ba504945e26","their_label":"other party","alias":"","their_role":"","initiator":"external","updated_at":"2019-11-04T23:32:32.5609321Z","invitation_key":"none","routing_state":"none","connection_id":"a","invitation_mode":"none"}`

**Comment by sudeshrshetty** [comment]
No work needed.
fixed as part of https://github.com/hyperledger/aries-framework-go/pull/704
@rolsonquadras please confirm
