### ISSUE TITLE
DID Resolution

### ISSUE THREAD

**Issue by alikic** [hyperledger/aries-framework-go#71]
Resolving DIDs is the act of fetching the DID document associated with the DID from a datasource identified by the DID's method (read the DID spec for details on the DID identifier format). If the DID has a fragment, then only the portion of the DID document identified by that fragment is returned.

The solution's architecture must support plugging in additional "drivers" for other DID methods.

Example: resolving a kid with value did:example:123456789abcdefghi#1 results in fetching the DID document associated to did:example:123456789abcdefghi and returning the element in the array of publicKey that has the id set to did:example:123456789abcdefghi#1. Note that the DID's context provides a hint as to where in the DID document to search for the element identified; in this case, kid implies that we are searching for a key, hence why in this case we would narrow the search to the publicKey array.

References
- DID spec: https://w3c-ccg.github.io/did-spec/
- DID Resolution spec: https://w3c-ccg.github.io/did-resolution/

**Comment by llorllale** [comment]
Closing because it is being handled in #86
