### ISSUE TITLE
DID Exchange: Implicit Invitation

### ISSUE THREAD

**Issue by troyronda** [hyperledger/aries-framework-go#718]
Send DID exchange request without invitation

- Initiator knows public DID.
- Wants to request DID exchange without prior invitation.

**Comment by llorllale** [comment]
Yes, this is part of the RFC. We're missing this functionality.

I pushed a small PR to aries-rfcs in an attempt to clarify implicit invitations a bit: hyperledger/aries-rfcs#295

**Comment by rolsonquadras** [comment]
@troyronda @llorllale This issue looks similar to https://github.com/hyperledger/aries-framework-go/issues/500. If so, we can close one of these.

**Comment by fqutishat** [comment]
@sandrask
