### ISSUE TITLE
Provide necessary data for service state machine

### ISSUE THREAD

**Issue by soluchok** [hyperledger/aries-framework-go#724]
The client should provide necessary information to the service by passing the proper interface to the Continue function. 

Requirements:

* add `ProtocolDependency(thID) Dependency` function to the client
* Dependency interface looks like following
```
type Dependency interface {
	Invitation() didexchange.Invitation
	Destinations() []service.Destination
}
```

Invitation() function returns an invitation related to the introduction, the invitation can be `public` or `private`
public - means that the agent has another agent's invitation
private - means own agent invitation (unique)
`public` and `private` means nothing to the service (it is just an explanation)
The private invitation should be registered once when the `Client` is created and it cannot be changed.
The public invitation can be received from `Client API` e.g `SendProposalWithInvitation(inv *didexchange.Invitation, dest *service.Destination)` previously saved it to the store and retrieved it by  thID. 
The public invitation has more priority.If we have a public invitation for the given thID it must be returned, otherwise, we need to return the private invitation.
What if there is no public or private invitation?
It is ok, in that case, we should return a nil value.

Destinations() - returns the destination value (to whom we need to send it)
e.g sending a public proposal we will have only one destination
e.g sending proposal (no public invitation) we will have two destinations

Part of https://github.com/hyperledger/aries-framework-go/issues/269

**Comment by llorllale** [comment]
@soluchok 

I want to clarify something:

> public - means that the agent has another agent's invitation
> private - means own agent invitation (unique)

The invitations that the *Introducer* handles are *never their own*. They are always of other agents (introducees). What the introducer does is forward these invitations around.

**Comment by soluchok** [comment]
@llorllale correct! What I want to do is to prepare data before the state machine will be started! 
The idea is to provide one Dependency interface which should provide all necessary data to the state machine (better to collect it before the protocol starts).  For instance, state machine calls `Invitation(thID)` function  (see dependency interface) and Client must provide the right invitation
According to a state machine, `Invitation(thID)` function will return a different result. 
e.g for introducer we will get an invitation from DB by given thID, for introducee DB will be empty, so we will return a `private` invitation (this logic on the client-side)
It allows us to avoid handling the action events by their type (on the client-side or even layer up) and do something like that b.Continue(WithSomeParam(),WithSomethingElse())

**Comment by llorllale** [comment]
@soluchok 

Nevermind the naming which doesn't seem right to me: how does that usage allow the Introducer to specify the invitation when they receive a `request`?

**Comment by soluchok** [comment]
This is a good question :) I was about to ask you about it. We can provide the method `PrepareDependency` and this method must be called before executing `Continue` function.  
PrepareDependency can be a kind of `SendProposal` function but it will not use HandelOutbound function, it will just prepare the right interface which can be received by calling `client.ProtocolDependency(thID)`.

usage: we received a Request message
```
select{
case action<-actions:
// TODO: one dest1 can be determined somehow from the incoming message
if action.Msg.Type == RequestMsgType{
    client.PrepareDependency(action.Msg, inv, dest1, dest2)
}
action.Continue(client.ProtocolDependency(thID))
}
```
P.S Any ideas are welcome :)
Note: ClientDependency interface can be fully controlled by the end-user, the idea of ProtocolDependency and PrepareDependency functions is just to simplify the usage and to prevent simple mistakes

**Comment by soluchok** [comment]
@llorllale ^ Does it make sense?

**Comment by llorllale** [comment]
@soluchok the solution that ended up [merged](https://github.com/hyperledger/aries-framework-go/pull/737/files#diff-53f48d9400b55325b3f6a88c6129625eR78) does not fit the flow that begins with the Introducer receiving a `request` message. If the Introducer wishes to immediately reply with an invitation (presumably a public invitation) then there should be no need to specify the destination here because you'd be replying to the sender of the `request`, and their destination should already be tied to their connection record, which itself should have already been tied by the state machine when receiving the `request` and before firing the event to the application layer.

I think "destinations" should be passed to `Continue()` only when sending out proposals, and even then I question the choice of having the application pass in lower level details like `destinations` when instead it could just pass a handle to the relationship (eg. theirDID or connectionID).

**Comment by soluchok** [comment]
It is not a problem.
Currently, we have two functions to handle this.
```
HandleRequest(msg service.DIDCommMsg, dest1, dest2 *service.Destination) 
HandleRequestWithInvitation(msg service.DIDCommMsg, inv *didexchange.Invitation, dest *service.Destination)
```
they can be changed to
```
HandleRequest(msg service.DIDCommMsg, dest1) 
HandleRequestWithInvitation(msg service.DIDCommMsg, inv *didexchange.Invitation)
```

I will correct this state machine after merging my current PR. The next issue(PR) will be about it.
