### ISSUE TITLE
Allow DIDComm protocols to use DIDs to identify agents sending/receiving messages

### ISSUE THREAD

**Issue by Moopli** [hyperledger/aries-framework-go#725]
For one-to-one agent communication, protocol code shouldn't need to include code for retrieving destination parameters when sending messages, and shouldn't need to decipher the identity of a sender when receiving messages. Instead, the outbound dispatcher or helper functions should retrieve destination parameters given a DID, and inbound transport should provide the sender's DID, so protocols can operate solely using DIDs if they don't need more customized functionality.

**Comment by Moopli** [comment]
We could also return the connection ID when we unpack.

**Comment by Moopli** [comment]
Rewrote the issue, since it was describing one potential solution rather than the problem to be solved.

**Comment by fqutishat** [comment]
@troyronda  @rolsonquadras  @Moopli  
#998  need this functionality
