### ISSUE TITLE
Sign response using recepientKey

### ISSUE THREAD

**Issue by sandrask** [hyperledger/aries-framework-go#728]
As per spec we should sign exchange response using recipientKey from invitation if the flow was started from invitation. This can be done upon completing #676 that allows for correlation between exchange-request and invitation using pthid.

We also need to handle the case of implicit invitation #718

**Comment by fqutishat** [comment]
@talwinder50

**Comment by talwinder50** [comment]
assign to me

**Comment by llorllale** [comment]
Note: the exchange *request* is not signed as per the current version of the spec. It's the *response* that is signed.

**Comment by sandrask** [comment]
@llorllale it was a typo. updated description
