### ISSUE TITLE
Controller : DID Exchange using Public DIDs.

### ISSUE THREAD

**Issue by sudeshrshetty** [hyperledger/aries-framework-go#788]
@troyronda @llorllale 
Should we use public DID as a bool in `connections/create-invitation` or string?

if we choose to use bool, then there should be a mechanism to configure public DID for given agent.

**Comment by troyronda** [comment]
@sudeshrshetty I assume aca-py is using a bool?

**Comment by fqutishat** [comment]
This has been implemented.
