### ISSUE TITLE
ci: include test files in linter

### ISSUE THREAD

**Issue by troyronda** [hyperledger/aries-framework-go#84]
This should fail:
https://github.com/hyperledger/aries-framework-go/pull/66/files#diff-7de7681f01cd73c279bb10b7466c2953R127

**Comment by llorllale** [comment]
I could not reproduce this by moving around closing brackets in the `master` branch

**Comment by troyronda** [comment]
@llorllale Are you saying this is happening only on CircleCI not locally?

**Comment by llorllale** [comment]
@troyronda no. I just pulled @talwinder50's [branch](https://github.com/talwinder50/aries-framework-go/tree/issue-48) and `make lint` runs with no issues

**Comment by rolsonquadras** [comment]
@troyronda I think it didn't fail as test files are ignored from linter check - https://github.com/hyperledger/aries-framework-go/blob/master/.golangci.yml#L15

**Comment by troyronda** [comment]
We shouldn’t exclude test files. I’ll update description.
