### ISSUE TITLE
Feat: Convert Verifiable Credential into Verifiable Presentation

### ISSUE THREAD

**Issue by haardikk21** [hyperledger/aries-framework-go#861]
**What I'm trying to do**
- Business logic might be required to convert a VC into a VP, for example in case of a wallet provider. We should have a function to do it.

**Expected result**
have a function like `vc.CreatePresentation()` which returns a valid presentation struct.

**Comment by fqutishat** [comment]
@kdimak

**Comment by kdimak** [comment]
After closing VC documentation #885 , there is a simple `*Credential.Presentation()` method:
https://github.com/hyperledger/aries-framework-go/blob/2cccd53074901097c9e26fbfa7eca1ec8a093ec6/pkg/doc/verifiable/credential.go#L759

@haardikk21 does this new method suite your needs? can we close this issue?

**Comment by haardikk21** [comment]
> After closing VC documentation #885 , there is a simple `*Credential.Presentation()` method:
> https://github.com/hyperledger/aries-framework-go/blob/2cccd53074901097c9e26fbfa7eca1ec8a093ec6/pkg/doc/verifiable/credential.go#L759
> 
> @haardikk21 does this new method suite your needs? can we close this issue?

As discussed, since we have a different issue for tracking JWS signing/verification for VC's and VP's - we can close this for now. Eventually, we would want to build the proof when converting a VC into a VP though.

**Comment by troyronda** [comment]
@haardikk21 I'm not quite understanding your comment. Is there an open issue tracking your feature request? Which issue number?
