### ISSUE TITLE
Update RFC -0036 with the type to didComm.org 

### ISSUE THREAD

**Issue by talwinder50** [hyperledger/aries-framework-go#868]
"@type": "did:sov:BzCbsNYhMrjHiqZDTUASHg;spec/issue-credential/1.0/offer-credential",
https://github.com/hyperledger/aries-rfcs/tree/master/features/0036-issue-credential

RFC needs to be versioned to update the type to : 
"@type": "https://didcomm.org/issue-credential/1.0/offer-credential",

**Comment by troyronda** [comment]
For our purposes, assume that this has already happened. The larger community is debating timing of this string switch for RFCs that are already in Accepted state.
