### ISSUE TITLE
Project Build information in README

### ISSUE THREAD

**Issue by rolsonquadras** [hyperledger/aries-framework-go#89]
Currently, the project [README](https://github.com/hyperledger/aries-framework-go/blob/master/README.md) file doesn't contain build instructions. Need to add basic project build instructions to the README file.

**Comment by rolsonquadras** [comment]
@llorllale @troyronda Can you assign the issue to me and move to In-progress in [Framework development board](https://github.com/hyperledger/aries-framework-go/projects/2) ?

**Comment by troyronda** [comment]
@rolsonquadras done
