### ISSUE TITLE
Design New crypto logic using the newer JWE format defined in Aries RFC-0334

### ISSUE THREAD

**Issue by Baha-sk** [hyperledger/aries-framework-go#913]
In order to make the Packer work with JWE envelopes that are FIPS/NIST compliant, a new format was introduced in [RFC-0334](https://github.com/hyperledger/aries-rfcs/pull/334)

On top of this new format, the JWE packer should call crypto operations and working with keys securely with pluggable KMS. For this reason, there's a need to use a `tried and tested` framework that can manage these operations for the Packer. One strong candidate is [Tink](https://github.com/google/tink).

A new design document is needed to lay down the work needed for implementing the above topics.

**Comment by troyronda** [comment]
As mentioned in a followup comment, we must also add support for P-256 curves in addition to X25519.
