### ISSUE TITLE
Controller API for DID exchange

### ISSUE THREAD

**Issue by sudeshrshetty** [hyperledger/aries-framework-go#93]
Open API server : REST API endpoints for did exchange protocol.
Write Open API (swagger) spec to generate server for did exchange protocol endpoints.

epic #67

**Comment by sudeshrshetty** [comment]
Note: {id} is connection id here

GET ​/exchange/connections Query agent-to-agent connections
GET ​/exchange/connections​/{id} Fetch a single connection record


POST ​/exchange​/create-invitation Create a new exchange invitation
POST ​/exchange​/receive-invitation Receive a new exchange invitation
POST ​/exchange​/{id}​/accept-invitation Accept a stored connection invitation
Note: if `--auto-accept-invites --auto-accept-requests` are disabled then agent should manually accept invitation

POST ​/exchange​/{id}​/send-exchange-request Send DID exchange request
POST ​/exchange​/{id}​/send-exchange-response Send DID exchange response

@rolsonquadras @llorllale @troyronda

**Comment by troyronda** [comment]
I think the full name of the protocol should be used in the path (e.d., did-exchange).

**Comment by sudeshrshetty** [comment]
@troyronda updated

**Comment by llorllale** [comment]
@troyronda that would conflict with one of the objectives for 0.1.0 (see the wiki)

**Comment by sudeshrshetty** [comment]
> @troyronda that would conflict with one of the objectives for 0.1.0 (see the [wiki](https://wiki.hyperledger.org/display/ARIES/Framework+Go+v0.1.0))

Not sure which one you are talking about, @llorllale

**Comment by llorllale** [comment]
@sudeshrshetty I meant this objective for one of the demos:

> The controller API in this framework will be closely aligned with the one in aries-cloudagent-python with the goal of demonstrating interoperability.

This objective requires us to implement the same REST interface as aries-cloudagent-python

**Comment by sudeshrshetty** [comment]
@llorllale I agree, but as per your earlier comment on #68 
connections endpoint are not valid anymore, instead it should be replaced by [DID Exchange](https://github.com/hyperledger/aries-rfcs/blob/master/features/0023-did-exchange/README.md)

[Agent cloud python](https://github.com/hyperledger/aries-cloudagent-python) yet to make that update. Either we wait or go ahead with our implementations.

May be a followup story for later to track your concern about interoperability?

**Comment by llorllale** [comment]
@sudeshrshetty sorry - I wasn't clear [here](https://github.com/hyperledger/aries-framework-go/issues/68#issuecomment-520558486): that note was just an observation, not a request for a change.

Story remains the same so far - we need should be interoperable with controller API in aries-cloudagent-python. But @troyronda also suggests implementing `did-exchange` paths *in addition* to these `connection` ones. `connection` could be treated as a synonym for `did-exchange`.

**Comment by sudeshrshetty** [comment]
@llorllale alright then, I will create a new story for connections endpoints since they are out of this story's scope.
So, Should we move below 2 endpoint methods out of did-exchange endpoint? or Should I keep them as it is because I feel 'connections' may retire in future?

GET ​/did-exchange/connections Query agent-to-agent connections
GET ​/did-exchange/connections​/{id} Fetch a single connection record
@troyronda @rolsonquadras

**Comment by troyronda** [comment]
Yes - lets create a new story to deal with the connection synonym issue.

How were those two endpoint methods specified in the cloudagent? @sudeshrshetty

**Comment by sudeshrshetty** [comment]
@troyronda did-exchange protocol is not yet available in cloudagent.
If we retire connections protocol in future, we may need to move these 2 under did-exchange.
Better we duplicate these 2 endpoints under did-exchange and connections.

**Comment by sudeshrshetty** [comment]
@troyronda @llorllale created https://github.com/hyperledger/aries-framework-go/issues/121
please update milestone and other required tags
