### ISSUE TITLE
Pass VC Test Suite

### ISSUE THREAD

**Issue by kdimak** [hyperledger/aries-framework-go#947]
Failing tests:
- Bad cardinality: https://github.com/w3c/vc-test-suite/issues/96, https://github.com/w3c/vc-test-suite/issues/97. Try to find solution on the **aries** side.
- Unknown public key for VC: https://github.com/w3c/vc-test-suite/issues/101. Use the RS256 public key from [config.json.example](https://github.com/w3c/vc-test-suite/blob/gh-pages/config.json.example), prepare own JWS and create PR at VC Test Suite. Also, consider replacing JWS of `verifiableCredential` inside VP (e.g. [example-016-jwt-presentation.jsonld](https://github.com/w3c/vc-test-suite/blob/gh-pages/test/vc-data-model-1.0/input/example-016-jwt-presentation.jsonld)).

Fail CI checks on test suite failure.

**Comment by kdimak** [comment]
Remaining 2 failing tests:
- Bad cardinality: w3c/vc-test-suite#96, w3c/vc-test-suite#97. Try to find solution on the aries side.
should be fixed in #992 .
After that, we will be able to send the good looking report to the VC Test Suite.

**Comment by troyronda** [comment]
Prior to sending the Report, we should see if there is feedback on the JWS signature patch issue.
