### ISSUE TITLE
Add support for Ed25519VerificationKey2018

### ISSUE THREAD

**Issue by llorllale** [hyperledger/aries-framework-go#96]
Add support for the `Ed25519VerificationKey2018` signature suite such that `publicKey` entries can be added to the DID documents and the owners of those DIDs can prove ownership to a Verifier.

This is the first in a series of cryptographic suites that will need to be implemented by the framework in order to be interoperable.

Links:
* [Ed25519 Signature 2018](https://w3c-dvcg.github.io/lds-ed25519-2018/)
* [Linked Data Signatures](https://w3c-dvcg.github.io/ld-signatures/)
* [Linked Data Cryptographic Suite Registry](https://w3c-ccg.github.io/ld-cryptosuite-registry)

**Comment by llorllale** [comment]
Part of epic #35

**Comment by dmitrizagidulin** [comment]
This is great! 
(Also, the LD Crypto Suite related specs are currently being updated / refreshed, so please feel free to open issues and ask questions if something is unclear or looks out of date.)
