### ISSUE TITLE
Generic Message Service - Registration & Handling

### ISSUE THREAD

**Issue by sudeshrshetty** [hyperledger/aries-framework-go#970]
Design : https://wiki.hyperledger.org/pages/viewpage.action?pageId=24778806

**Comment by sudeshrshetty** [comment]
_Design_	


```
// MessageService interface to be registered by external code
type MessageService interface {
	service.InboundHandler
	Accept(header *service.Header) bool
        Name() string 
}
   
```

```
// MessageHandler returned by context
type MessageHandler struct {
     MessageService
     Outbound
}
```

-   Registering

       _// Passing as an option to aries.New()_
        framework, err := aries.New(..., WithMessageService(msgSvc))

      _// Registering to already created context_
       framework, err := aries.New(opts...)
	ctx, err := framework.Context()
	ctx.RegisterMessageService(msgSvc)

-   Handling Inbound message
    // following function from registered message service will be called based on accept criteria
     HandleInbound(msg *DIDCommMsg, myDID, theirDID string) (string, error)	

-   Sending outbound message
     // lookup for registered message service in context which returns composite objecr containing registered MessageService + outbound dispatcher
        ctx.MessageHandler(name).Send(....)

**Comment by troyronda** [comment]
I am generally reluctant to have external code using context methods directly (rather than treating as an opaque handle).

Specifically ctx.MessageHandler above.

**Comment by sudeshrshetty** [comment]
@troyronda 

You mean something like
msgHandle := messagehandle.New(ctx)
// For outbound
msgHandle.Find(name).Send(...)

Dynamic registration may suffer from this

**Comment by troyronda** [comment]
@sudeshrshetty Yes that would be an approach.

**Comment by sudeshrshetty** [comment]
@troyronda What's you opinion about passing MessageService through aries new opts?

**Comment by sudeshrshetty** [comment]
@troyronda I am thinking of having something like this 

msgHandle := messagehandle.New(ctx)
messagehandle.RegisterService(msgSvc....)
// For outbound
msgHandle.Find(name).Send(...)

**Comment by llorllale** [comment]
The design of `MessageService` says an implementation is to be supplied by client code:

```go
// MessageService interface to be registered by external code
type MessageService interface {
	service.InboundHandler
	Accept(header *service.Header) bool
        Name() string 
}
```

`service.InboundHandler` handles raw DIDComm messages. Client code should be spared this complexity and should be handed the decrypted payload (the contents of the `data` attribute).

`service.Header` is also a raw DIDComm artifact. Clients should not have to deal with this low-level DIDComm stuff.

**Comment by sudeshrshetty** [comment]
@llorllale I agree, 
`service.InboundHandler` gets called after unpacking....
https://github.com/hyperledger/aries-framework-go/blob/master/pkg/didcomm/common/service/service.go#L19

So client code implementation gets unpacked DIDComm msg.

Header is only for filtering if client chooses to go with complex acceptance criteria

**Comment by llorllale** [comment]
@sudeshrshetty I've opened an issue re: the header: #1040 .

Regarding your point about clients accepting complex criteria: the RFC-in-progress by @Moopli is heavy on the concept of "registration". This suggests to me that client implementations of the `MessageService` need to register themselves to the component that dispatches unpacked messages of this protocol. As such, I don't see the need to pass the `purpose` back to the clients - they already know what they signed up for in the first place.

**Comment by sudeshrshetty** [comment]
@llorllale multiple clients can register to same message service for different purposes, that's the reason why we have acceptance criteria here. 
`client_1` registers for `purpose_1`
`client_2` registers for `purpose_2`

**Comment by llorllale** [comment]
@sudeshrshetty @troyronda it seems like the requirements have changed a lot from what's in the wiki. What are the updated requirements for this feature?
