### ISSUE TITLE
Add Default implementation for JWE Authcrypt Packer

### ISSUE THREAD

**Issue by Baha-sk** [hyperledger/aries-framework-go#986]
There should be a default implementation of JWE Authcrypt envelope as described in [RFC-0334](https://github.com/hyperledger/aries-rfcs/tree/master/features/0334-jwe-envelope) JWE Envelope

- [x] Create ECDH-1PU Tink primitive #1905

**Comment by troyronda** [comment]
- Nested JWS version
- ECDH-1PU version
