### ISSUE TITLE
Create DID Resolver HTTP Binding (from W3C DID resolver spec) - AKA Universal Resolver

### ISSUE THREAD

**Issue by fqutishat** [hyperledger/aries-framework-go#99]
Write universal resolver that use http client to resolve did from specific URL.

epic #86

**Comment by troyronda** [comment]
More generally we should support:
> DID Resolution functionality over the [HTTP(S) binding](https://w3c-ccg.github.io/did-resolution/#bindings-https)

Rather than calling this specific to the "Universal Resolver". I will update the title.
